Repository debops/debops, pull requests merged in 2020-07, with the labels that each got.

#1404 Add variable to set chrony cmdport, which was disabled in #1236
  ansible/roles/ntp/defaults/main.yml
  ansible/roles/ntp/templates/etc/chrony/chrony.conf.j2
Labels: change, status: completed

#1405 [postfix] Use long form in master.cf
  CHANGELOG.rst
  ansible/roles/postfix/templates/etc/postfix/master.cf.j2
Labels: change, status: completed, tag: mail services

#1406 [debops.icinga_web] fix typo in doc
  ansible/roles/icinga_web/defaults/main.yml
Labels: documentation, status: completed

#1408 Missing secret role import
  ansible/roles/sudo/tasks/main.yml
Labels: bug, status: completed

#1409 [rsnapshot] Fix dry run error
  CHANGELOG.rst
  ansible/roles/rsnapshot/tasks/main.yml
Labels: change, status: completed

#1411 [owncloud] Fix dry run errors
  CHANGELOG.rst
  ansible/roles/owncloud/tasks/tarball.yml
Labels: change, status: completed, tag: Ansible dry-run mode

#1413 [debops.postgresql] Drop role/database if requested and fix issues with when clauses
  ansible/roles/postgresql/tasks/main.yml
Labels: change, priority: medium, tag: PostgreSQL, tag: database

#1414 Various updates in LDAP support
  CHANGELOG.rst
  LICENSES/OLDAP-2.8.txt
  ansible/playbooks/ldap/init-directory.yml
  ansible/roles/ldap/tasks/ldap_tasks.yml
  ansible/roles/ldap/tasks/main.yml
  ansible/roles/slapd/COPYRIGHT
  ansible/roles/slapd/defaults/main.yml
  ansible/roles/slapd/files/etc/ldap/schema/debops/dyngroup.schema
  ansible/roles/slapd/files/etc/ldap/schema/debops/eduperson.schema
  ansible/roles/slapd/files/etc/ldap/schema/debops/mailservice.schema
  ansible/roles/slapd/meta/main.yml
  docs/ansible/roles/slapd/ldap-dit.rst
  docs/ansible/roles/slapd/ldap-schema.rst
  docs/ansible/roles/slapd/slapd-overlays.rst
  docs/news/upgrades.rst
Labels: change, priority: medium, tag: LDAP

#1416 Fix bool conditions based on non-bool values
  ansible/roles/pki/defaults/main.yml
  ansible/roles/root_account/defaults/main.yml
  ansible/roles/system_users/defaults/main.yml
Labels: bug, priority: high

#1419 [apt] Install gnupg before downloading PGP keys
  CHANGELOG.rst
  ansible/roles/apt/defaults/main.yml
Labels: change, priority: medium

#1425 [docs] fix typos in CHANGELOG
  CHANGELOG.rst
Labels: documentation, status: completed

#1427 [docs] Add project roadmap
  docs/index.rst
  docs/meta/roadmap.rst
Labels: documentation, status: completed

#1429 [docs] Rename 'roadmap' to 'goals', more precise
  docs/index.rst
  docs/meta/goals.rst
  docs/meta/philosophy.rst
Labels: documentation, status: completed

#1430 [docs] Review and spell check goals
  docs/meta/goals.rst
Labels: documentation

#1433 Fix issues detected by shellcheck v0.7.0
  ansible/roles/docker_gen/templates/etc/init.d/docker-gen.j2
  ansible/roles/lxc/files/usr/local/lib/lxc/lxc-destroy-systemd-instance
  ansible/roles/lxc/files/usr/local/lib/lxc/lxc-net-resolvconf
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
  ansible/roles/slapd/files/usr/local/sbin/slapd-config
  lib/tests/jane
Labels: bug, status: completed

#1436 Update CODEOWNERS file, add CREDITS file
  CODEOWNERS
  CREDITS
Labels: documentation, status: completed

#1437 Various improvments
  CHANGELOG.rst
  CODEOWNERS
  CREDITS
  ansible/debops-contrib-playbooks/service/homeassistant-nginx.yml
  ansible/debops-contrib-playbooks/service/homeassistant-plain.yml
  ansible/debops-contrib-playbooks/service/homeassistant.yml
  ansible/roles/debops-contrib.homeassistant/defaults/main.yml
  ansible/roles/debops-contrib.homeassistant/docs/playbooks/homeassistant-nginx.yml
  ansible/roles/debops-contrib.homeassistant/docs/playbooks/homeassistant-plain.yml
  ansible/roles/debops-contrib.homeassistant/docs/playbooks/homeassistant.yml
  ansible/roles/debops-contrib.homeassistant/tasks/main.yml
  ansible/roles/docker_registry/defaults/main.yml
  ansible/roles/mosquitto/defaults/main.yml
  ansible/roles/nodejs/defaults/main.yml
  ansible/roles/resources/defaults/main.yml
  ansible/roles/resources/tasks/main.yml
  docs/ansible/roles/resources/defaults-detailed.rst
  docs/ansible/roles/resources/getting-started.rst
Labels: change, priority: medium

#1434 [roundcube] Discard cleandb.sh stdout
  ansible/roles/roundcube/tasks/deploy_roundcube.yml
Labels: change, status: completed, tag: mail services

#1438 Add myself to CODEOWNERS and CREDITS
  CODEOWNERS
  CREDITS
Labels: documentation, status: completed

#1435 [owncloud] add new LDAP options to owncloud__config
  ansible/roles/owncloud/defaults/main.yml
Labels: new feature, status: completed, tag: LDAP

#1442 add example for environment
  docs/ansible/roles/cron/defaults-detailed.rst
Labels: documentation, status: completed

#1445 Add 'filebeat' Ansible role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/agent/all.yml
  ansible/playbooks/agent/filebeat.yml
  ansible/playbooks/service/filebeat.yml
  ansible/roles/filebeat/COPYRIGHT
  ansible/roles/filebeat/defaults/main.yml
  ansible/roles/filebeat/meta/main.yml
  ansible/roles/filebeat/tasks/main.yml
  ansible/roles/filebeat/templates/etc/ansible/facts.d/filebeat.fact.j2
  ansible/roles/filebeat/templates/etc/filebeat/filebeat.yml.j2
  ansible/roles/filebeat/templates/etc/filebeat/snippets.d/snippet.yml.j2
  ansible/roles/global_handlers/handlers/filebeat.yml
  ansible/roles/global_handlers/handlers/main.yml
  docs/ansible/role-index.rst
  docs/ansible/roles/filebeat/defaults-detailed.rst
  docs/ansible/roles/filebeat/getting-started.rst
  docs/ansible/roles/filebeat/index.rst
  docs/ansible/roles/filebeat/man_description.rst
  docs/ansible/roles/filebeat/man_index.rst
  docs/ansible/roles/filebeat/man_synopsis.rst
Labels: new feature, status: completed, tag: logging

#1446 Fix various DokuWiki issues
  CHANGELOG.rst
  ansible/roles/dokuwiki/defaults/main.yml
  ansible/roles/dokuwiki/tasks/main.yml
  ansible/roles/dokuwiki/templates/srv/www/dokuwiki/sites/public/conf/plugins.protected.php.j2
Labels: bug, status: completed
