Repository debops/debops, pull requests merged in 2020-08, with the labels that each got.

#1450 Enable more Roundcube plugins, fix small LDAP issues
  CHANGELOG.rst
  ansible/playbooks/service/roundcube.yml
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/slapd/defaults/main.yml
  ansible/roles/slapd/files/etc/ldap/schema/debops/mailservice.schema
  docs/ansible/roles/ldap/ldap-dit.rst
  docs/ansible/roles/roundcube/defaults-detailed.rst
  docs/ansible/roles/roundcube/getting-started.rst
  docs/ansible/roles/roundcube/guides.rst
  docs/ansible/roles/roundcube/index.rst
  docs/ansible/roles/roundcube/ldap-dit.rst
  docs/ansible/roles/roundcube/man_index.rst
  docs/ansible/roles/slapd/ldap-acl.rst
Labels: change, status: completed, tag: LDAP, tag: mail services

#1452 [roundcube] Update Roundcube version to v1.4.7
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/roundcube/meta/watch-roundcubemail
Labels: change, status: completed, tag: mail services, tag: version upgrade

#1453 [roundcube] Don't unnecessarily create LDAP object
  ansible/roles/roundcube/defaults/main.yml
Labels: change, tag: LDAP, tag: mail services

#1454 [LDAP] Make POSIX integration optional
  CHANGELOG.rst
  ansible/playbooks/bootstrap-ldap.yml
  ansible/roles/ldap/defaults/main.yml
  ansible/roles/ldap/templates/etc/ansible/facts.d/ldap.fact.j2
  ansible/roles/nslcd/defaults/main.yml
  ansible/roles/sshd/defaults/main.yml
  ansible/roles/sudo/defaults/main.yml
  ansible/roles/system_groups/defaults/main.yml
  ansible/roles/system_users/defaults/main.yml
  docs/ansible/roles/ldap/getting-started.rst
  docs/ansible/roles/ldap/ldap-posix.rst
  docs/ansible/roles/sshd/getting-started.rst
  docs/ansible/roles/sudo/getting-started.rst
Labels: change, status: completed, tag: LDAP, tag: provisioning

#1423 [ntp] Don't try to disable systemd-timesyncd if not available
  CHANGELOG.rst
  ansible/roles/ntp/tasks/install.yml
Labels: change, priority: medium

#1439 Update nginx security directives
  ansible/roles/nginx/defaults/main.yml
  ansible/roles/nginx/templates/etc/nginx/nginx.conf.j2
  ansible/roles/nginx/templates/etc/nginx/sites-available/default.conf.j2
  ansible/roles/nginx/templates/etc/nginx/snippets/ssl.conf.j2
  docs/ansible/roles/nginx/getting-started.rst
Labels: change, priority: high, tag: nginx, tag: security

#1459 Nginx and docs fixes and improvements
  ansible/roles/nginx/defaults/main.yml
  ansible/roles/nginx/templates/etc/nginx/snippets/ssl.conf.j2
  docs/ansible/roles/mosquitto/getting-started.rst
  docs/ansible/roles/nginx/getting-started.rst
Labels: change, status: completed, tag: nginx

#1457 [doc] Various minor edits
  CREDITS
  docs/ansible/roles/gunicorn/virtualenv-support.rst
  docs/ansible/roles/postgresql/defaults-detailed.rst
  docs/ansible/roles/postgresql/getting-started.rst
  docs/ansible/roles/postgresql_server/getting-started.rst
  docs/ansible/roles/users/defaults-detailed.rst
Labels: documentation, priority: medium

#1462 [roundcube] Update Roundcube version to 1.4.8
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/roundcube/meta/watch-roundcubemail
Labels: change, status: completed, tag: mail services, tag: version upgrade

#1464 [ci] Update JANE_LOG_PATTERN variables
  .gitlab-ci.yml
Labels: change, status: completed, tag: Continuous Integration

#1463 [dhcrelay] Add debops.dhcrelay role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/net/all.yml
  ansible/playbooks/net/dhcrelay.yml
  ansible/playbooks/service/dhcrelay.yml
  ansible/roles/dhcrelay/COPYRIGHT
  ansible/roles/dhcrelay/defaults/main.yml
  ansible/roles/dhcrelay/meta/main.yml
  ansible/roles/dhcrelay/tasks/main.yml
  ansible/roles/dhcrelay/templates/etc/ansible/facts.d/dhcrelay.fact.j2
  ansible/roles/dhcrelay/templates/etc/default/isc-dhcp-relay.j2
  ansible/roles/global_handlers/handlers/dhcrelay.yml
  ansible/roles/global_handlers/handlers/main.yml
  docs/ansible/role-index.rst
  docs/ansible/roles/dhcrelay/getting-started.rst
  docs/ansible/roles/dhcrelay/index.rst
  docs/ansible/roles/dhcrelay/man_description.rst
  docs/ansible/roles/dhcrelay/man_index.rst
  docs/ansible/roles/dhcrelay/man_synopsis.rst
  docs/news/upgrades.rst
Labels: new feature, status: completed, tag: DHCP, tag: networking

#1472 [dhcrelay] Import ansible_plugins for dpkg_divert
  ansible/roles/dhcrelay/tasks/main.yml
Labels: bug, status: completed, tag: DHCP

#1475 playbooks: Add tool for safe upgrade and reboot.
  ansible/playbooks/tools/upgrade-reboot.yml
Labels: new feature, status: completed

#1481 Multiple fixes for various issues
  CHANGELOG.rst
  ansible/roles/docker_server/defaults/main.yml
  ansible/roles/system_users/defaults/main.yml
  ansible/roles/system_users/tasks/main.yml
  docs/introduction/getting-started.rst
Labels: bug, status: completed, tag: DNS

#1483 Changes in the GitLab-CI dependency graph
  .gitlab-ci.yml
  ansible/playbooks/service/dovecot.yml
Labels: change, status: completed, tag: Continuous Integration

#1484 [owncloud] Make Nextcloud 18.0 the default release
  ansible/roles/owncloud/defaults/main.yml
  ansible/roles/owncloud/meta/watch-nextcloud
Labels: change, priority: medium, tag: version upgrade

#1485 Various small fixes
  CHANGELOG.rst
  ansible/playbooks/service/etherpad.yml
  ansible/roles/apt_install/defaults/main.yml
  ansible/roles/etherpad/defaults/main.yml
  ansible/roles/phpipam/defaults/main.yml
  ansible/roles/phpipam/meta/watch-phpipam
Labels: bug, status: completed

#1431 [netbox] WIP: Update to Netbox 2.8
  CHANGELOG.rst
  ansible/roles/netbox/defaults/main.yml
  ansible/roles/netbox/meta/main.yml
  ansible/roles/netbox/meta/watch-netbox
  ansible/roles/netbox/tasks/main.yml
  ansible/roles/netbox/templates/usr/local/lib/netbox/configuration.py.j2
  docs/ansible/roles/netbox/defaults-detailed.rst
  docs/ansible/roles/netbox/getting-started.rst
Labels: change, priority: medium, tag: application, tag: version upgrade

#1489 [pki] Install 'acme-tiny' from OS repositories
  CHANGELOG.rst
  ansible/roles/pki/defaults/main.yml
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
  ansible/roles/pki/tasks/acme_tiny.yml
Labels: bug, status: completed, tag: Let's Encrypt/ACME, tag: PKI

#1490 Updated 'bootstrap-ansible' path in CI and switch to newer pip package
  Vagrantfile
  ansible/roles/controller/defaults/main.yml
  ansible/roles/controller/tasks/main.yml
  ansible/roles/docker_server/defaults/main.yml
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/python/defaults/main.yml
Labels: change, status: completed, tag: Continuous Integration, tag: Python, tag: upkeep

#1491 Fix 'python-pip-whl' package situation
  Vagrantfile
  ansible/roles/docker_server/defaults/main.yml
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/python/defaults/main.yml
Labels: bug, status: completed, tag: Python

#1474 [doc] User guide: Universal Configuration
  docs/ansible/roles/ansible_plugins/getting-started.rst
  docs/index.rst
  docs/introduction/configuration.rst
  docs/user-guide/universal-configuration.rst
Labels: documentation, priority: high

#1493 Docs fixes and [homeassistant] Serve static files directly by the webserver
  CHANGELOG.rst
  ansible/debops-contrib-playbooks/README.rst
  ansible/debops-contrib-playbooks/service/checkmk_agent.yml
  ansible/roles/homeassistant/defaults/main.yml
  ansible/roles/homeassistant/docs/getting-started.rst
  ansible/roles/homeassistant/tasks/main.yml
  ansible/roles/rsyslog/defaults/main.yml
  bin/debops-optimize-old
  docs/ansible/roles/cryptsetup/guides.rst
  docs/ansible/roles/icinga/deployment.rst
  docs/ansible/roles/lxc/defaults-detailed.rst
  docs/ansible/roles/mailman/defaults-detailed.rst
  docs/ansible/roles/mailman/getting-started.rst
  docs/ansible/roles/redis_server/defaults-detailed.rst
  docs/includes/global.rst
  docs/meta/philosophy.rst
Labels: documentation

#1494 Add forgotten variable in rsyslog configuration
  CHANGELOG.rst
  ansible/roles/homeassistant/tasks/main.yml
  ansible/roles/rsyslog/defaults/main.yml
Labels: bug, status: completed, tag: logging

#1495 [docs] The DebOps 'stable-1.1' branch is retired
  docs/news/releases.rst
Labels: documentation, status: completed
