Repository debops/debops, pull requests merged in 2020-03, with the labels that each got.

#1288 [docs] Improve collection upgrade command example
  INSTALL.rst
Labels: documentation, status: completed

#1291 [etesync] Fix wrong Jinja comment tag
  ansible/roles/etesync/templates/etc/etesync-server/secret.txt.j2
Labels: bug, status: completed

#1294 Bugfixes in MinIO server and client roles
  CHANGELOG.rst
  ansible/roles/mcli/templates/etc/ansible/facts.d/mcli.fact.j2
  ansible/roles/minio/templates/etc/ansible/facts.d/minio.fact.j2
  ansible/roles/minio/templates/etc/systemd/system/minio@.service.j2
Labels: bug, status: completed

#1292 [owncloud] Make Nextcloud 17.0 the default release
  CHANGELOG.rst
  ansible/roles/owncloud/defaults/main.yml
  ansible/roles/owncloud/meta/watch-nextcloud
Labels: change, priority: high, tag: version upgrade

#1297 [owncloud] No parameter validate in module file.
  ansible/roles/owncloud/tasks/setup_owncloud.yml
Labels: bug, status: completed

#1300 [debops.postgresql_server] Config day of the month to perform monthly backups
  ansible/roles/postgresql_server/defaults/main.yml
  ansible/roles/postgresql_server/templates/etc/default/autopostgresqlbackup.j2
  ansible/roles/postgresql_server/templates/usr/sbin/autopostgresqlbackup.j2
Labels: new feature, status: completed, tag: PostgreSQL, tag: backup, tag: database

#1302 [nginx] Set HSTS header regardless of status code
  CHANGELOG.rst
  ansible/roles/nginx/templates/etc/nginx/sites-available/default.conf.j2
Labels: change, status: completed, tag: nginx, tag: webserver

#1304 Adding new Ubuntu LTS
  ansible/roles/php/defaults/main.yml
Labels: change, status: completed, tag: upkeep

#1309 [nginx] Install fact script earlier
  ansible/roles/nginx/tasks/main.yml
Labels: bug, priority: high, tag: webserver
