Repository debops/debops, pull requests merged in 2020-06, with the labels that each got.

#1358 [debops.mount] omit owner/group if not specified when ensuring mount …
  ansible/roles/mount/tasks/main.yml
Labels: change, status: completed

#1362 [roundcube] Install pgsql module for php if needed
  ansible/roles/roundcube/defaults/main.yml
Labels: change, status: completed, tag: mail services

#1363 Various role updates
  CHANGELOG.rst
  ansible/roles/ansible/defaults/main.yml
  ansible/roles/core/defaults/main.yml
  ansible/roles/core/tasks/main.yml
  ansible/roles/core/templates/etc/ansible/facts.d/uuid.fact.j2
  ansible/roles/lxd/defaults/main.yml
  ansible/roles/lxd/meta/watch-lxd
  ansible/roles/roundcube/tasks/main.yml
Labels: change, status: completed, tag: mail services, tag: version upgrade

#1365 [lxd] Workaround for git commit verification
  ansible/roles/lxd/defaults/main.yml
Labels: bug, status: completed

#1366 [ci] Use 4096 GB of RAM for 'lxd' test
  .gitlab-ci.yml
Labels: change, status: completed, tag: Continuous Integration

#1367 [mailman] Redesign the role, switch to Mailman 3.x
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/service/mailman.yml
  ansible/roles/mailman/COPYRIGHT
  ansible/roles/mailman/defaults/main.yml
  ansible/roles/mailman/defaults/main/core_configuration.yml
  ansible/roles/mailman/defaults/main/dependent.yml
  ansible/roles/mailman/defaults/main/environment.yml
  ansible/roles/mailman/defaults/main/hyperkitty_configuration.yml
  ansible/roles/mailman/defaults/main/ldap.yml
  ansible/roles/mailman/defaults/main/templates.yml
  ansible/roles/mailman/defaults/main/web_configuration.yml
  ansible/roles/mailman/files/patches/add-moderator-link.patch
  ansible/roles/mailman/files/patches/ignore-commands-from-nonmembers.patch
  ansible/roles/mailman/files/patches/prune-alias-list.patch
  ansible/roles/mailman/files/patches/remove-upper-list-name.patch
  ansible/roles/mailman/files/scripts/convert-mailman-to-utf8
  ansible/roles/mailman/handlers/main.yml
  ansible/roles/mailman/meta/main.yml
  ansible/roles/mailman/tasks/main.yml
  ansible/roles/mailman/templates/etc/ansible/facts.d/mailman.fact.j2
  ansible/roles/mailman/templates/etc/mailman/mm_cfg.py.j2
  ansible/roles/mailman/templates/etc/mailman/postfix_transport.j2
  ansible/roles/mailman/templates/etc/mailman3/mailman-hyperkitty.cfg.j2
  ansible/roles/mailman/templates/etc/mailman3/mailman-web.py.j2
  ansible/roles/mailman/templates/etc/mailman3/mailman.cfg.j2
  ansible/roles/mailman/templates/etc/systemd/system/mailman3-web.service.d/dependencies.conf.j2
  ansible/roles/mailman/templates/etc/systemd/system/mailman3.service.d/dependencies.conf.j2
  ansible/roles/mailman/templates/lookup/mailman__languages.j2
  ansible/roles/mailman/templates/lookup/mailman__site_language.j2
  docs/ansible/roles/ldap/ldap-dit.rst
  docs/ansible/roles/mailman/defaults-detailed.rst
  docs/ansible/roles/mailman/getting-started.rst
  docs/ansible/roles/mailman/index.rst
  docs/ansible/roles/mailman/ldap-dit.rst
  docs/ansible/roles/mailman/mailman2-migration.rst
  docs/ansible/roles/mailman/man_description.rst
  docs/ansible/roles/mailman/man_index.rst
  docs/ansible/roles/mailman/man_synopsis.rst
Labels: change, status: completed, tag: mail services, tag: version upgrade

#1368 [mailman] Fix missing timezone fact support
  ansible/roles/mailman/defaults/main/web_configuration.yml
Labels: bug, status: completed, tag: mail services

#1374 Minor fixes and improvments
  CHANGELOG.rst
  INSTALL.rst
  ansible/debops-contrib-playbooks/service/apparmor.yml
  ansible/roles/apt/defaults/main.yml
  ansible/roles/debops-contrib.apparmor/defaults/main.yml
  ansible/roles/debops-contrib.homeassistant/meta/main.yml
  ansible/roles/debops-contrib.kodi/defaults/main.yml
  ansible/roles/debops-contrib.kodi/meta/main.yml
  ansible/roles/influxdb_server/templates/etc/influxdb/influxdb.conf.j2
  ansible/roles/postgresql_server/defaults/main.yml
  ansible/roles/python/defaults/main.yml
  ansible/roles/python/tasks/main.yml
  ansible/roles/python/templates/etc/pip.conf.j2
  docs/news/upgrades.rst
  setup.py
Labels: change, priority: high

#1376 Reorder 'netbase' and 'resolvconf' roles in plays
  ansible/playbooks/bootstrap-ldap.yml
  ansible/playbooks/bootstrap.yml
  ansible/playbooks/common.yml
Labels: change, status: completed, tag: PKI

#1377 Reorder Changelog entries
  CHANGELOG.rst
Labels: documentation, status: completed

#1378 Changelog entry reorder
  CHANGELOG.rst
Labels: documentation, status: completed

#1379 [pki] Use 'inventory_hostname' in directory paths
  CHANGELOG.rst
  ansible/roles/pki/defaults/main.yml
  ansible/roles/pki/tasks/main.yml
  ansible/roles/pki/templates/lookup/pki_env_secret_directories.j2
Labels: change, status: completed, tag: PKI

#1381 [debops.resources] allow empty content in file
  ansible/roles/resources/tasks/main.yml
Labels: change, status: completed

#1383 [nginx] Support for configurable PHP location
  ansible/roles/nginx/templates/etc/nginx/sites-available/php.conf.j2
  docs/ansible/roles/nginx/defaults-detailed.rst
Labels: change, status: completed, tag: nginx

#1384 Miscellaneous fixes
  ansible/roles/debops-contrib.foodsoft/defaults/main.yml
  ansible/roles/debops-contrib.volkszaehler/defaults/main.yml
  ansible/roles/debops_api/defaults/main.yml
  ansible/roles/dnsmasq/defaults/main.yml
  ansible/roles/dokuwiki/defaults/main.yml
  ansible/roles/hashicorp/defaults/main.yml
  ansible/roles/hashicorp/templates/etc/ansible/facts.d/hashicorp.fact.j2
  ansible/roles/icinga_web/defaults/main.yml
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/librenms/defaults/main.yml
  ansible/roles/lxc/defaults/main.yml
  ansible/roles/netbase/defaults/main.yml
  ansible/roles/postldap/defaults/main.yml
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/rsnapshot/templates/etc/cron/rsnapshot-wrapper.j2
  ansible/roles/slapd/defaults/main.yml
  ansible/roles/snmpd/defaults/main.yml
Labels: bug, status: completed

#1385 [snmpd] Fix mismatched bracket
  ansible/roles/snmpd/tasks/main.yml
Labels: bug, status: completed

#1386 Additional fixes after fact changes
  ansible/roles/mariadb/templates/etc/ansible/facts.d/mariadb.fact.j2
  ansible/roles/php/tasks/main_env.yml
  ansible/roles/postgresql_server/defaults/main.yml
Labels: bug, status: completed

#1387 Additional fixes
  ansible/roles/dokuwiki/defaults/main.yml
  lib/tests/scripts/postfix-send-mail
Labels: bug, status: completed

#1388 Additional fixes for mismatched brackets
  ansible/roles/gitlab/defaults/main.yml
  ansible/roles/slapd/defaults/main.yml
Labels: bug, status: completed

#1389 [pki] Fixed symbolic link paths for openssl selfsigned root cert
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
Labels: change, status: completed, tag: PKI

#1392 Rename 'debops.debops' role to 'debops.controller'
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/app/all.yml
  ansible/playbooks/app/controller.yml
  ansible/playbooks/app/debops.yml
  ansible/playbooks/service/controller.yml
  ansible/roles/controller/COPYRIGHT
  ansible/roles/controller/defaults/main.yml
  ansible/roles/controller/handlers/main.yml
  ansible/roles/controller/meta/main.yml
  ansible/roles/controller/tasks/main.yml
  ansible/roles/controller/templates/etc/debops.cfg.j2
  ansible/roles/debops/tasks/main.yml
  ansible/roles/debops/templates/etc/debops.cfg.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/controller/getting-started.rst
  docs/ansible/roles/controller/index.rst
  docs/ansible/roles/controller/man_description.rst
  docs/ansible/roles/controller/man_index.rst
  docs/ansible/roles/controller/man_synopsis.rst
  docs/ansible/roles/debops/man_synopsis.rst
  docs/news/upgrades.rst
Labels: change, status: completed

#1393 [mailman] Provide redirect from old installation
  ansible/roles/mailman/defaults/main/dependent.yml
Labels: new feature, status: completed, tag: mail services

#1395 Small updates in 'mailman' role
  ansible/roles/mailman/defaults/main/dependent.yml
  docs/meta/community.rst
Labels: change, status: completed, tag: mail services

#1397 Fix home directory expansion in DebOps scripts
  CHANGELOG.rst
  debops/config.py
  tests/test_config.py
Labels: bug, status: completed

#1394 Expand ~ in XDG_* env var
  debops/config.py
Labels: bug, priority: high

#1402 [docs] Add description of "global variables"
  docs/index.rst
  docs/user-guide/global-variables.rst
Labels: documentation, status: completed
