Repository debops/debops, pull requests merged in 2021-03, with the labels that each got.

#1646 [ci] Install Cryptography from Debian in Vagrant
  CHANGELOG.rst
  Vagrantfile
Labels: change, status: completed, tag: Continuous Integration

#1651 Small fixes in documentation and DebOps scripts
  CHANGELOG.rst
  bin/debops-update
  lib/ansible-galaxy/make-collection
Labels: bug, status: completed

#1652 Correct section tag for docker.tmpfs
  ansible/roles/gitlab_runner/templates/etc/gitlab-runner/config.toml.j2
Labels: change, status: completed, tag: Docker, tag: GitLab

#1655 [cron] Fix role execution on non-systemd hosts
  CHANGELOG.rst
  ansible/roles/cron/defaults/main.yml
Labels: bug, status: completed

#1656 Saslauthd uid correction
  ansible/roles/saslauthd/defaults/main.yml
Labels: bug, status: completed, tag: LDAP, tag: mail services

#1663 Quick fixes to recently found bugs related to handlers
  ansible/playbooks/service/rabbitmq_management.yml
  ansible/roles/backup2l/tasks/main.yml
  ansible/roles/dokuwiki/defaults/main.yml
  ansible/roles/librenms/defaults/main.yml
  ansible/roles/phpipam/defaults/main.yml
  ansible/roles/rabbitmq_management/defaults/main.yml
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/volkszaehler/defaults/main.yml
Labels: bug, status: completed, tag: Continuous Integration

#1669 Add configuration for ansible-lint
  .ansible-lint
Labels: internal, status: completed, tag: Continuous Integration

#1667 fix to support dependent roles
  ansible/roles/sudo/tasks/main.yml
Labels: bug, status: completed

#1661 add lxc__default_container_backing_store variable
  ansible/roles/lxc/defaults/main.yml
  ansible/roles/lxc/tasks/main.yml
Labels: new feature, status: completed, tag: containers

#1660 Correctly react to various ways python files are reported by "file"
  lib/tests/check-pep8
Labels: bug, status: completed, tag: Continuous Integration

#1659 Fix debops-default not finding playbooks in <projectdir>/debops
  debops/__init__.py
Labels: bug, status: completed
