Repository debops/debops, pull requests merged in 2021-08, with the labels that each got.

#1786 Various fixes for issues found during Debian Bullseye deployment
  CHANGELOG.rst
  ansible/roles/ferm/defaults/main.yml
  ansible/roles/libvirt/defaults/main.yml
  ansible/roles/libvirtd/defaults/main.yml
  ansible/roles/lxc/defaults/main.yml
  ansible/roles/lxc/tasks/main.yml
  ansible/roles/netbase/templates/etc/ansible/facts.d/netbase.fact.j2
  ansible/roles/proc_hidepid/tasks/main.yml
  ansible/roles/proc_hidepid/templates/etc/systemd/system/user@.service.d/hidepid.conf.j2
  ansible/roles/sysctl/defaults/main.yml
  docs/ansible/roles/unbound/defaults-detailed.rst
Labels: change, status: completed, tag: LXC, tag: networking, tag: provisioning, tag: upkeep

#1788 Update fail2ban/getting-started.rst
  docs/ansible/roles/fail2ban/getting-started.rst
Labels: documentation, status: completed

#1782 [cryptsetup] Disable checksum computation
  ansible/roles/cryptsetup/tasks/manage_devices.yml
Labels: change, status: completed

#1790 [slapd] Add attributes in 'mailservice' schema
  CHANGELOG.rst
  ansible/roles/slapd/defaults/main.yml
  ansible/roles/slapd/files/etc/ldap/schema/debops/mailservice.schema
  docs/news/upgrades.rst
Labels: change, status: completed, tag: LDAP, tag: mail services

#1787 [debops.lxc] port latest connection plugin lxc_ssh.py
  ansible/plugins/connection_plugins/lxc_ssh.py
Labels: change, status: completed, tag: LXC

#1791 A few improvements in the 'nginx' role
  ansible/roles/nginx/defaults/main.yml
  ansible/roles/nginx/templates/etc/nginx/sites-available/default.conf.j2
  docs/news/upgrades.rst
Labels: change, status: completed, tag: nginx

#1794 Add TLS encryption to Elasticsearch and Kibana
  CHANGELOG.rst
  ansible/roles/elasticsearch/defaults/main.yml
  ansible/roles/elasticsearch/tasks/authentication.yml
  ansible/roles/elasticsearch/tasks/main.yml
  ansible/roles/elasticsearch/templates/etc/ansible/facts.d/elasticsearch.fact.j2
  ansible/roles/elasticsearch/templates/usr/share/elasticsearch/jdk/conf/security/java.policy.j2
  ansible/roles/kibana/defaults/main.yml
  ansible/roles/kibana/tasks/main.yml
  docs/ansible/roles/elasticsearch/clustering.rst
  docs/ansible/roles/elasticsearch/defaults-detailed.rst
  docs/ansible/roles/elasticsearch/getting-started.rst
  docs/ansible/roles/kibana/getting-started.rst
Labels: new feature, status: completed, tag: security, tag: PKI, tag: Elastic

#1807 [sudo] Use correct string as version in facts
  CHANGELOG.rst
  ansible/roles/sudo/templates/etc/ansible/facts.d/sudo.fact.j2
Labels: bug, status: completed, tag: Ansible facts

#1781 feat(apt_preferences): Preset: Prefer NeuroDebian but don't upgrade; feat(mariadb_server): Define ports used for Galera in /etc/services
  .mailmap
  CHANGELOG.rst
  CREDITS
  ansible/playbooks/service/mariadb_server.yml
  ansible/roles/apt_preferences/defaults/main.yml
  ansible/roles/mariadb_server/defaults/main.yml
  ansible/roles/owncloud/defaults/main.yml
  ansible/roles/resolvconf/defaults/main.yml
  ansible/roles/tor/tasks/main.yml
  docs/ansible/roles/system_users/control-user.rst
Labels: change, status: completed

#1805 automatically upgrade icinga2
  ansible/playbooks/service/icinga.yml
  ansible/roles/icinga/defaults/main.yml
Labels: new feature, status: completed, tag: monitoring

#1804 [debops] Fix version parsing in several facts.d scripts
  ansible/roles/dnsmasq/templates/etc/ansible/facts.d/dnsmasq.fact.j2
  ansible/roles/docker_server/templates/etc/ansible/facts.d/docker_server.fact.j2
  ansible/roles/extrepo/templates/etc/ansible/facts.d/extrepo.fact.j2
  ansible/roles/freeradius/templates/etc/ansible/facts.d/freeradius.fact.j2
  ansible/roles/icinga/templates/etc/ansible/facts.d/icinga.fact.j2
  ansible/roles/redis_sentinel/templates/etc/ansible/facts.d/redis_sentinel.fact.j2
  ansible/roles/redis_server/templates/etc/ansible/facts.d/redis_server.fact.j2
Labels: change, status: completed, tag: Ansible facts

#1803 [debops] Fix PKI hook uninstallation
  ansible/roles/nginx/tasks/main.yml
  ansible/roles/postfix/tasks/main.yml
  ansible/roles/prosody/tasks/main.yml
Labels: bug, status: completed, tag: PKI

#1802 [redis_server] Listen on IPv6 as well as IPv4
  ansible/roles/redis_server/defaults/main.yml
Labels: change, status: completed, tag: database

#1801 [debops] support security key SSH keys
  ansible/playbooks/ldap/init-directory.yml
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/system_users/defaults/main.yml
Labels: change, status: completed, tag: SSH

#1798 [slapd] Add explicit dependency on libldap-common
  ansible/roles/slapd/defaults/main.yml
Labels: change, status: completed, tag: LDAP

#1797 [sssd] sudo support fixes
  ansible/roles/sssd/defaults/main.yml
  ansible/roles/sudo/defaults/main.yml
Labels: change, status: completed, tag: LDAP

#1792 [ldap] Update device iface regex to support systemd-nspawn veth
  ansible/roles/ldap/defaults/main.yml
Labels: change, status: completed, tag: LDAP

#1796 [dhcpd] Quote host-identifier
  CHANGELOG.rst
  ansible/roles/dhcpd/templates/etc/dhcp/macro_host.j2
Labels: bug, status: completed, tag: DHCP

#1777 Allow user override via envvar
  docs/Makefile
Labels: documentation, status: completed

#1774 Enable TCP sysctl performance flags
  ansible/roles/sysctl/defaults/main.yml
Labels: new feature, status: completed, tag: kernel

#1773 Document a tinc star network configuration
  docs/ansible/roles/tinc/examples.rst
Labels: documentation, status: completed, tag: networking

#1808 [apt] fix typo in task name
  ansible/roles/apt/tasks/main.yml
Labels: documentation, status: completed

#1766 Owncloud fix ldap config
  ansible/roles/owncloud/tasks/ldap.yml
Labels: bug, status: completed, tag: Nextcloud

#1811 Updates concerning Debian Bullseye release
  CHANGELOG.rst
  ansible/roles/docker_server/defaults/main.yml
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/ipxe/templates/srv/tftp/template.ipxe.j2
  docs/ansible/roles/ipxe/defaults-detailed.rst
Labels: change, status: completed, tag: provisioning, tag: Docker, tag: upkeep

#1812 Add watch files for Bullseye, fix Hashicorp uscan warnings
  ansible/roles/hashicorp/meta/watch-atlas-upload-cli
  ansible/roles/hashicorp/meta/watch-consul
  ansible/roles/hashicorp/meta/watch-consul-replicate
  ansible/roles/hashicorp/meta/watch-consul-template
  ansible/roles/hashicorp/meta/watch-docker-base
  ansible/roles/hashicorp/meta/watch-docker-basetool
  ansible/roles/hashicorp/meta/watch-envconsul
  ansible/roles/hashicorp/meta/watch-nomad
  ansible/roles/hashicorp/meta/watch-otto
  ansible/roles/hashicorp/meta/watch-packer
  ansible/roles/hashicorp/meta/watch-serf
  ansible/roles/hashicorp/meta/watch-terraform
  ansible/roles/hashicorp/meta/watch-vault
  ansible/roles/hashicorp/meta/watch-vault-ssh-helper
  ansible/roles/ipxe/meta/watch-firmware-bullseye
  ansible/roles/ipxe/meta/watch-netboot-bullseye
Labels: change, status: completed

#1816 [apache] Enable the force keyword for site configuration
  ansible/roles/apache/tasks/main.yml
Labels: change, status: completed, tag: webserver
