Repository debops/debops, pull requests merged in 2021-09, with the labels that each got.

#1825 Refresh the 'debops.preseed' role, fix various bugs
  CHANGELOG.rst
  ansible/playbooks/bootstrap-ldap.yml
  ansible/playbooks/bootstrap-sss.yml
  ansible/playbooks/bootstrap.yml
  ansible/playbooks/common.yml
  ansible/playbooks/service/preseed.yml
  ansible/roles/elasticsearch/defaults/main.yml
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/kibana/defaults/main.yml
  ansible/roles/ldap/tasks/main.yml
  ansible/roles/netbase/templates/etc/ansible/facts.d/netbase.fact.j2
  ansible/roles/preseed/COPYRIGHT
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/preseed/tasks/main.yml
  ansible/roles/preseed/templates/etc/ansible/facts.d/preseed.fact.j2
  ansible/roles/preseed/templates/srv/www/preseed/configs/d-i/debian-destroy.cfg.j2
  ansible/roles/preseed/templates/srv/www/preseed/configs/d-i/debian-destroy.sh.j2
  ansible/roles/preseed/templates/srv/www/preseed/configs/d-i/debian.cfg.j2
  ansible/roles/preseed/templates/srv/www/preseed/configs/d-i/debian.sh.j2
  ansible/roles/preseed/templates/srv/www/sites/debian-preseed/public/postinst.sh.j2
  ansible/roles/preseed/templates/srv/www/sites/debian-preseed/public/preseed.cfg.j2
  docs/ansible/roles/preseed/defaults-detailed.rst
  docs/ansible/roles/preseed/getting-started.rst
  docs/news/upgrades.rst
Labels: change, status: completed, tag: provisioning

#1824 unattended_upgrades: Add simplest example
  docs/ansible/roles/unattended_upgrades/defaults-detailed.rst
Labels: documentation, status: completed

#1826 [apt] Add a way to purge APT packages
  CHANGELOG.rst
  ansible/roles/apt/defaults/main.yml
  ansible/roles/apt/tasks/main.yml
Labels: new feature, status: completed, tag: provisioning

#1822 Set correct value for mariadb__package_map
  ansible/roles/mariadb/defaults/main.yml
Labels: bug, status: completed, tag: MariaDB

#1819 [minidlna] Fix typos
  docs/ansible/roles/minidlna/defaults-detailed.rst
Labels: documentation, status: completed

#1828 Add 'debops.telegraf' role, co-authored with @ser :)
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/agent/all.yml
  ansible/playbooks/agent/telegraf.yml
  ansible/playbooks/service/telegraf.yml
  ansible/roles/ansible_plugins/filter_plugins/toml.py
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/global_handlers/handlers/telegraf.yml
  ansible/roles/telegraf/COPYRIGHT
  ansible/roles/telegraf/defaults/main.yml
  ansible/roles/telegraf/meta/main.yml
  ansible/roles/telegraf/tasks/main.yml
  ansible/roles/telegraf/templates/etc/ansible/facts.d/telegraf.fact.j2
  ansible/roles/telegraf/templates/etc/telegraf/telegraf.conf.j2
  ansible/roles/telegraf/templates/etc/telegraf/telegraf.d/plugin.conf.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/telegraf/defaults-detailed.rst
  docs/ansible/roles/telegraf/getting-started.rst
  docs/ansible/roles/telegraf/index.rst
  docs/ansible/roles/telegraf/man_description.rst
  docs/ansible/roles/telegraf/man_index.rst
  docs/ansible/roles/telegraf/man_synopsis.rst
Labels: new feature, status: completed, tag: monitoring, tag: InfluxData

#1829 Add usage information in `pki-authority` script
  ansible/roles/pki/files/secret/pki/lib/pki-authority
Labels: documentation, status: completed, tag: PKI

#1830 Edit application list
  docs/ansible/role-index.rst
Labels: documentation, status: completed

#1832 [docs] Clarify the value type of a variable
  ansible/roles/pki/defaults/main.yml
Labels: documentation, status: completed, tag: PKI

#1768 + custom_log and error_log for fullly customization of CustomLog and ErrorLog Directive
  ansible/roles/apache/templates/etc/apache2/conf-available/local-debops_apache.conf.j2
  ansible/roles/apache/templates/etc/apache2/sites-available/default.conf.j2
Labels: change, priority: high, tag: logging, tag: webserver

#1770 + [debops.apache] alias_path to customize the alias path of Alias Directive
  ansible/roles/apache/templates/etc/apache2/conf-available/local-debops_apache.conf.j2
  ansible/roles/apache/templates/etc/apache2/sites-available/default.conf.j2
Labels: change, priority: high, tag: webserver

#1754 [redis_server] Facts version and passwordless istances
  ansible/roles/redis_server/templates/etc/ansible/facts.d/redis_server.fact.j2
Labels: bug, priority: medium

#1835 [telegraf] Add Telegraf account to UNIX groups
  ansible/roles/telegraf/defaults/main.yml
  ansible/roles/telegraf/tasks/main.yml
Labels: change, status: completed, tag: monitoring, tag: InfluxData

#1834 apt: add keys tag
  ansible/roles/apt/tasks/main.yml
  docs/ansible/roles/apt/getting-started.rst
Labels: change, status: completed

#1836 [owncloud] Fix legacy webserver support
  CHANGELOG.rst
  ansible/roles/owncloud/defaults/main.yml
Labels: bug, status: completed, tag: nginx, tag: Nextcloud

#1837 Add 'debops.lldpd' role, remove LLDP support from 'debops.snmpd'
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/common.yml
  ansible/playbooks/service/lldpd.yml
  ansible/playbooks/service/snmpd.yml
  ansible/roles/global_handlers/handlers/lldpd.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/global_handlers/handlers/snmpd.yml
  ansible/roles/lldpd/COPYRIGHT
  ansible/roles/lldpd/defaults/main.yml
  ansible/roles/lldpd/meta/main.yml
  ansible/roles/lldpd/tasks/main.yml
  ansible/roles/lldpd/templates/etc/ansible/facts.d/lldpd.fact.j2
  ansible/roles/lldpd/templates/etc/default/lldpd.j2
  ansible/roles/lldpd/templates/etc/lldpd.d/template.conf.j2
  ansible/roles/snmpd/defaults/main.yml
  ansible/roles/snmpd/tasks/main.yml
  ansible/roles/snmpd/templates/etc/default/lldpd.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/lldpd/defaults-detailed.rst
  docs/ansible/roles/lldpd/getting-started.rst
  docs/ansible/roles/lldpd/index.rst
  docs/ansible/roles/lldpd/man_description.rst
  docs/ansible/roles/lldpd/man_index.rst
  docs/ansible/roles/lldpd/man_synopsis.rst
  docs/ansible/roles/snmpd/getting-started.rst
Labels: new feature, status: completed, tag: networking

#1818 Zabbix agent
  .gitlab-ci.yml
  ansible/playbooks/agent/all.yml
  ansible/playbooks/agent/zabbix_agent.yml
  ansible/playbooks/service/zabbix_agent.yml
  ansible/roles/zabbix_agent/COPYRIGHT
  ansible/roles/zabbix_agent/defaults/main.yml
  ansible/roles/zabbix_agent/meta/main.yml
  ansible/roles/zabbix_agent/tasks/main.yml
  ansible/roles/zabbix_agent/templates/etc/ansible/facts.d/zabbix_agent.fact.j2
  ansible/roles/zabbix_agent/templates/etc/zabbix/zabbix_agentd.conf.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/zabbix_agent/defaults-detailed.rst
  docs/ansible/roles/zabbix_agent/getting-started.rst
  docs/ansible/roles/zabbix_agent/index.rst
  docs/ansible/roles/zabbix_agent/man_description.rst
  docs/ansible/roles/zabbix_agent/man_index.rst
  docs/ansible/roles/zabbix_agent/man_synopsis.rst
Labels: new feature, priority: high, tag: monitoring

#1838 Add support for Zabbix Agent
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/agent/all.yml
  ansible/playbooks/agent/zabbix_agent.yml
  ansible/playbooks/service/zabbix_agent.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/global_handlers/handlers/zabbix_agent.yml
  ansible/roles/zabbix_agent/COPYRIGHT
  ansible/roles/zabbix_agent/defaults/main.yml
  ansible/roles/zabbix_agent/meta/main.yml
  ansible/roles/zabbix_agent/tasks/main.yml
  ansible/roles/zabbix_agent/templates/etc/ansible/facts.d/zabbix_agent.fact.j2
  ansible/roles/zabbix_agent/templates/etc/zabbix/zabbix_agentd.conf.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/zabbix_agent/defaults-detailed.rst
  docs/ansible/roles/zabbix_agent/getting-started.rst
  docs/ansible/roles/zabbix_agent/index.rst
  docs/ansible/roles/zabbix_agent/man_description.rst
  docs/ansible/roles/zabbix_agent/man_index.rst
  docs/ansible/roles/zabbix_agent/man_synopsis.rst
Labels: new feature, status: completed, tag: monitoring

#1785 WIP [pki] Use dns-ovh certbot
  ansible/roles/pki/defaults/main.yml
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
  ansible/roles/pki/tasks/main.yml
  docs/ansible/roles/pki/acme-certbot-integration.rst
  docs/ansible/roles/pki/acme-integration.rst
  docs/ansible/roles/pki/acme-tiny-integration.rst
  docs/ansible/roles/pki/index.rst
  docs/ansible/roles/pki/man_index.rst
  docs/ansible/roles/pki/pki-realms.rst
Labels: new feature, priority: high, tag: Let's Encrypt/ACME, tag: PKI

#1839 Small improvements in 'lldpd' role
  ansible/roles/lldpd/defaults/main.yml
  ansible/roles/lldpd/tasks/main.yml
Labels: change, status: completed, tag: networking

#1852 [pki] Fix permission issues in /etc/letsencrypt/
  ansible/roles/pki/defaults/main.yml
  ansible/roles/pki/files/etc/letsencrypt/renewal-hooks/post/000-fix-permissions
  ansible/roles/pki/tasks/certbot.yml
  ansible/roles/pki/tasks/main.yml
  ansible/roles/pki/templates/etc/letsencrypt/cli.ini.j2
  docs/ansible/roles/pki/defaults-detailed.rst
Labels: bug, status: completed, tag: Let's Encrypt/ACME, tag: PKI

#1854 [pki] Execute post-hook from certbot config file
  ansible/roles/pki/defaults/main.yml
Labels: change, status: completed, tag: Let's Encrypt/ACME, tag: PKI

#1857 Improve 'pki' documentation about 'certbot', fix small issues
  CHANGELOG.rst
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
  docs/ansible/roles/pki/acme-certbot-integration.rst
  docs/ansible/roles/pki/acme-tiny-integration.rst
Labels: documentation, status: completed, tag: Let's Encrypt/ACME, tag: PKI

#1859 [icinga_web] upgrade businessprocess module
  ansible/roles/icinga_web/defaults/main.yml
Labels: bug, status: completed, tag: version upgrade

#1862 [icinga_web] Update watch file for businessprocess
  ansible/roles/icinga_web/meta/watch-businessprocess
Labels: documentation, status: completed, tag: version upgrade
