Repository debops/debops, pull requests merged in 2021-02, with the labels that each got.

#1627 Add 'extrepo' role and integrate it with 'keyring' role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/service/extrepo.yml
  ansible/playbooks/sys/all.yml
  ansible/playbooks/sys/extrepo.yml
  ansible/roles/extrepo/COPYRIGHT
  ansible/roles/extrepo/defaults/main.yml
  ansible/roles/extrepo/meta/main.yml
  ansible/roles/extrepo/tasks/main.yml
  ansible/roles/extrepo/templates/etc/ansible/facts.d/extrepo.fact.j2
  ansible/roles/extrepo/templates/etc/extrepo/config.yaml.j2
  ansible/roles/keyring/tasks/main.yml
  docs/ansible/role-index.rst
  docs/ansible/roles/extrepo/defaults-detailed.rst
  docs/ansible/roles/extrepo/getting-started.rst
  docs/ansible/roles/extrepo/index.rst
  docs/ansible/roles/extrepo/man_description.rst
  docs/ansible/roles/extrepo/man_index.rst
  docs/ansible/roles/extrepo/man_synopsis.rst
  docs/ansible/roles/keyring/defaults-detailed.rst
Labels: new feature, status: completed, tag: provisioning

#1624 [redis_server] Add a way to overwrite save option
  ansible/roles/redis_server/templates/etc/redis/instance/ansible-redis-dynamic.conf.j2
  docs/ansible/roles/redis_server/defaults-detailed.rst
  docs/ansible/roles/redis_server/examples/instance_configuration_remove_list_item.yml
  docs/ansible/roles/redis_server/examples/instance_configuration_reset_list.yml
Labels: change, status: completed

#1625 [iscsi] Fix typo in target discovery task
  CHANGELOG.rst
  ansible/roles/iscsi/tasks/main.yml
Labels: bug, status: completed

#1628 [system_users] fix python version check
  ansible/roles/system_users/tasks/main.yml
Labels: bug, status: completed, tag: Python, tag: provisioning

#1630 [ipxe] Update Debian Buster release to 10.8
  CHANGELOG.rst
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/ipxe/meta/watch-firmware-buster
  ansible/roles/ipxe/meta/watch-netboot-buster
Labels: change, status: completed, tag: version upgrade

#1629 [slapd]: update defaults
  ansible/roles/slapd/defaults/main.yml
Labels: change, priority: medium, tag: LDAP

#1636 Fix issues detected by 'ansible-lint' 5.0.0
  .ansible-lint
  Dockerfile
  ansible/roles/etesync/defaults/main.yml
  ansible/roles/gitlab/defaults/main.yml
  ansible/roles/kodi/defaults/main.yml
  ansible/roles/libvirtd/defaults/main.yml
  ansible/roles/libvirtd_qemu/defaults/main.yml
  ansible/roles/mosquitto/defaults/main.yml
  ansible/roles/netbase/tasks/main.yml
  ansible/roles/netbox/defaults/main.yml
  ansible/roles/netbox/tasks/main.yml
  ansible/roles/owncloud/defaults/main.yml
  ansible/roles/resources/tasks/shell_commands.yml
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler-apache.yml
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler-nginx.yml
Labels: change, status: completed, tag: Continuous Integration

#1631 [netbox] Fix NetBox crash when it tried to send Emails
  CHANGELOG.rst
  ansible/roles/netbox/defaults/main.yml
  ansible/roles/netbox/tasks/main.yml
  ansible/roles/netbox/templates/usr/local/lib/netbox/configuration.py.j2
  docs/conf.py
Labels: bug

#1633 [sshd]: change defaults so port doesn't have to be specified twice
  ansible/roles/sshd/defaults/main.yml
Labels: change, status: completed

#1638 A few tweaks in the 'roundcube' role
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
Labels: change, status: completed, tag: mail services

#1640 [apt] Update security suite name
  CHANGELOG.rst
  ansible/roles/apt/defaults/main.yml
Labels: change, status: completed, tag: upkeep

#1641 fix minor typo
  docs/ansible/roles/freeradius/man_description.rst
Labels: documentation, status: completed

#1642 [sudo] Use @includedir with sudo 1.9.1+
  CHANGELOG.rst
  ansible/roles/sudo/tasks/main.yml
  ansible/roles/sudo/templates/etc/ansible/facts.d/sudo.fact.j2
Labels: bug, status: completed, tag: upkeep

#1645 Don't prepend 'debops.' prefix in role names
  CHANGELOG.rst
  bin/debops-defaults
Labels: bug, status: completed
