Repository debops/debops, pull requests merged in 2022-09, with the labels that each got.

#2189 Fix issues found by latest ansible-lint release
  ansible/playbooks/agent.yml
  ansible/playbooks/agent/all.yml
  ansible/playbooks/app.yml
  ansible/playbooks/app/all.yml
  ansible/playbooks/bootstrap-ldap.yml
  ansible/playbooks/bootstrap-sss.yml
  ansible/playbooks/bootstrap.yml
  ansible/playbooks/common.yml
  ansible/playbooks/env.yml
  ansible/playbooks/env/all.yml
  ansible/playbooks/hw.yml
  ansible/playbooks/hw/all.yml
  ansible/playbooks/net.yml
  ansible/playbooks/net/all.yml
  ansible/playbooks/service/cryptsetup.yml
  ansible/playbooks/service/dnsmasq.yml
  ansible/playbooks/service/lxc.yml
  ansible/playbooks/service/lxd.yml
  ansible/playbooks/service/mosquitto.yml
  ansible/playbooks/service/owncloud.yml
  ansible/playbooks/service/pdns.yml
  ansible/playbooks/service/tinc.yml
  ansible/playbooks/site.yml
  ansible/playbooks/srv.yml
  ansible/playbooks/srv/all.yml
  ansible/playbooks/sys.yml
  ansible/playbooks/sys/all.yml
  ansible/playbooks/virt.yml
  ansible/playbooks/virt/all.yml
  ansible/roles/etesync/defaults/main.yml
  ansible/roles/foodsoft/docs/playbooks/foodsoft.yml
  ansible/roles/iscsi/defaults/main.yml
  ansible/roles/nginx/tasks/nginx_servers.yml
  ansible/roles/owncloud/defaults/main.yml
  ansible/roles/pdns/defaults/main.yml
  ansible/roles/rails_deploy/vars/main.yml
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/tgt/defaults/main.yml
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler.yml
Labels: change, priority: medium, status: completed, tag: Continuous Integration

#2192 Support for custom APT keyring location
  CHANGELOG.rst
  ansible/roles/keyring/tasks/main.yml
  docs/ansible/roles/keyring/defaults-detailed.rst
Labels: new feature, priority: medium, status: completed, tag: APT packages

#2184 [keyring] Make keyring path configurable
  ansible/roles/keyring/tasks/main.yml
  docs/ansible/roles/keyring/defaults-detailed.rst
Labels: new feature, priority: high, tag: APT packages

#2191 [docs] Add faq about DebOps being slow
  docs/introduction/faq.rst
Labels: documentation, priority: medium, status: completed

#2193 Add FAQ answer about DebOps speed increases
  docs/introduction/faq.rst
Labels: documentation, priority: medium, status: completed

#2182 Allow ARM-based Macs to run docker_server role
  ansible/roles/docker_server/defaults/main.yml
Labels: change, priority: medium, status: completed, tag: Docker

#2180 [owncloud] Update ownCloud to 10.10
  ansible/roles/owncloud/defaults/main.yml
Labels: change, priority: high

#2194 Update ownCloud support
  CHANGELOG.rst
  ansible/roles/owncloud/defaults/main.yml
Labels: change, priority: medium, status: completed

#2179 [opensearch] Update OpenSearch to 2.2.0
  ansible/roles/opensearch/defaults/main.yml
  ansible/roles/opensearch/meta/watch-opensearch
Labels: change, priority: medium, status: completed, tag: database, tag: version upgrade

#2178 Issue2177: Bug fix with skeleton parameter set as /dev/null for user role
  ansible/roles/minio/tasks/main.yml
Labels: bug, priority: medium, status: completed
