Repository debops/debops, pull requests merged in 2022-01, with the labels that each got.

#1966 Add support for private APT repositories that require HTTP Basic Auth
  CHANGELOG.rst
  ansible/roles/apt/defaults/main.yml
  ansible/roles/apt/tasks/main.yml
  ansible/roles/extrepo/tasks/main.yml
  ansible/roles/keyring/defaults/main.yml
  ansible/roles/keyring/tasks/main.yml
  docs/ansible/roles/apt/defaults-detailed.rst
  docs/ansible/roles/keyring/defaults-detailed.rst
Labels: new feature, priority: medium, status: completed, tag: APT packages

#1965 feat(netbox): Upgrade to 3.1.3 and align with upstream defaults
  CHANGELOG.rst
  ansible/roles/netbox/COPYRIGHT
  ansible/roles/netbox/defaults/main.yml
  ansible/roles/netbox/meta/watch-netbox
  ansible/roles/netbox/templates/usr/local/lib/netbox/configuration.py.j2
  docs/ansible/roles/netbox/getting-started.rst
Labels: tag: networking, tag: version upgrade

#1968 [ipxe] Update release map for Bullseye 11.2
  ansible/roles/ipxe/defaults/main.yml
Labels: change, priority: high, status: completed, tag: version upgrade

#1971 [roundcube] Update Roundcube to 1.4.13
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/roundcube/meta/watch-roundcubemail
Labels: priority: high, tag: mail services, tag: security

#1961 feat(sshd): Keep SSH_CONNECTION env var when running commands with sudo
  CHANGELOG.rst
  ansible/playbooks/bootstrap-ldap.yml
  ansible/playbooks/bootstrap-sss.yml
  ansible/playbooks/common.yml
  ansible/playbooks/service/sshd.yml
  ansible/roles/sshd/defaults/main.yml
Labels: change, priority: medium, tag: SSH

#1960 Fix PKI regression #1946
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
Labels: bug, priority: high, status: completed, tag: PKI

#1975 Loop log spam fixes
  ansible/roles/ferm/tasks/main.yml
  ansible/roles/machine/tasks/main.yml
  ansible/roles/sysctl/tasks/main.yml
Labels: change, priority: medium, status: completed

#1978 [system_groups|system_users] Also detect if a host will be LDAP-enabled
  ansible/roles/system_groups/defaults/main.yml
  ansible/roles/system_users/defaults/main.yml
Labels: change, priority: medium, status: completed, tag: LDAP, tag: provisioning

#1983 Add 'keepalived' Ansible role, add missing Jinja templates
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/net/all.yml
  ansible/playbooks/net/keepalived.yml
  ansible/playbooks/service/keepalived.yml
  ansible/roles/apt/templates/etc/apt/auth.conf.d/template.conf.j2
  ansible/roles/global_handlers/handlers/keepalived.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/keepalived/COPYRIGHT
  ansible/roles/keepalived/defaults/main.yml
  ansible/roles/keepalived/meta/main.yml
  ansible/roles/keepalived/tasks/main.yml
  ansible/roles/keepalived/templates/etc/ansible/facts.d/keepalived.fact.j2
  ansible/roles/keepalived/templates/etc/keepalived/keepalived.conf.j2
  ansible/roles/keyring/templates/etc/apt/auth.conf.d/template.conf.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/keepalived/defaults-detailed.rst
  docs/ansible/roles/keepalived/getting-started.rst
  docs/ansible/roles/keepalived/index.rst
  docs/ansible/roles/keepalived/man_description.rst
  docs/ansible/roles/keepalived/man_index.rst
  docs/ansible/roles/keepalived/man_synopsis.rst
Labels: new feature, priority: medium, status: completed, tag: networking

#1979 Fixes before the next DebOps release: Fixes, NetBox netbox__config_custom option
  CHANGELOG.rst
  ansible/roles/apt_preferences/defaults/main.yml
  ansible/roles/etckeeper/defaults/main.yml
  ansible/roles/etckeeper/templates/etc/gitattributes.j2
  ansible/roles/netbox/defaults/main.yml
  ansible/roles/netbox/meta/watch-netbox
  ansible/roles/netbox/templates/usr/local/lib/netbox/configuration.py.j2
  ansible/roles/sshd/defaults/main.yml
  ansible/roles/unattended_upgrades/defaults/main.yml
  docs/meta/philosophy.rst
Labels: documentation

#1985 Update 'include' keyword in contrib playbooks
  ansible/debops-contrib-playbooks/service/all.yml
  ansible/debops-contrib-playbooks/service/foodsoft.yml
  ansible/debops-contrib-playbooks/service/homeassistant.yml
  ansible/debops-contrib-playbooks/service/volkszaehler.yml
Labels: change, priority: medium, status: completed
