Repository debops/debops, pull requests merged in 2022-11, with the labels that each got.

#2212 [ferm] Don't attempt to print an int
  ansible/roles/ferm/templates/etc/ferm/ferm.d/hashlimit.conf.j2
  ansible/roles/ferm/templates/etc/ferm/rules.d/rule.conf.j2
Labels: bug, priority: high, status: completed, tag: firewall

#2226 [python] Allow overriding /etc/pip.conf template
  ansible/roles/python/tasks/main.yml
Labels: change, priority: medium, status: completed, tag: Python

#2224 fix typos
  ansible/roles/icinga/defaults/main.yml
Labels: documentation, priority: medium, status: completed

#2222 role docker_server: fix typo in task name saving local facts
  ansible/roles/docker_server/tasks/main.yml
Labels: documentation, priority: medium, status: completed, tag: Docker

#2220 [ipxe] Fix yaml syntax.
  ansible/roles/ipxe/tasks/debian_netboot.yml
Labels: bug, priority: high, status: completed

#2219 [ifupdown] Fix mismerge from cherry-pick
  ansible/roles/ifupdown/templates/etc/network/interfaces.d/iface.j2
Labels: bug, priority: high, status: completed, tag: networking

#2213 Add log-driver to docker_server
  CHANGELOG.rst
  ansible/roles/docker_server/defaults/main.yml
  ansible/roles/docker_server/templates/etc/docker/daemon.json.j2
Labels: new feature, priority: medium, status: completed, tag: Docker
