Repository debops/debops, pull requests merged in 2022-07, with the labels that each got.

#2138 [pki] Change symlink to public cert if needed on renewal
  ansible/roles/pki/files/etc/letsencrypt/renewal-hooks/deploy/pki-realm-refresh-keys
Labels: bug, priority: medium, tag: Let's Encrypt/ACME, tag: PKI

#2135 [opensearch] Add new role debops.opensearch
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/service/opensearch.yml
  ansible/playbooks/srv/all.yml
  ansible/playbooks/srv/opensearch.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/global_handlers/handlers/opensearch.yml
  ansible/roles/opensearch/COPYRIGHT
  ansible/roles/opensearch/defaults/main.yml
  ansible/roles/opensearch/meta/main.yml
  ansible/roles/opensearch/meta/watch-opensearch
  ansible/roles/opensearch/tasks/main.yml
  ansible/roles/opensearch/templates/etc/ansible/facts.d/opensearch.fact.j2
  ansible/roles/opensearch/templates/etc/opensearch/jvm.options.j2
  ansible/roles/opensearch/templates/etc/opensearch/opensearch.yml.j2
  ansible/roles/opensearch/templates/etc/systemd/system/opensearch.service.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/opensearch/defaults-detailed.rst
  docs/ansible/roles/opensearch/getting-started.rst
  docs/ansible/roles/opensearch/index.rst
  docs/ansible/roles/opensearch/man_description.rst
  docs/ansible/roles/opensearch/man_index.rst
  docs/ansible/roles/opensearch/man_synopsis.rst
Labels: new feature, priority: low, tag: logging, tag: database

#2150 [resources] Add a way to replace strings in files
  CHANGELOG.rst
  ansible/roles/resources/defaults/main.yml
  ansible/roles/resources/tasks/main.yml
  docs/ansible/roles/resources/defaults-detailed.rst
Labels: new feature, priority: medium, status: completed

#2151 [opensearch] Fix issues found by ansible-lint
  ansible/roles/opensearch/defaults/main.yml
  ansible/roles/opensearch/tasks/main.yml
Labels: change, priority: medium, status: completed, tag: Continuous Integration

#2132 [pki] add acme_domains on initialization of realm
  ansible/roles/pki/tasks/main.yml
Labels: bug, priority: medium, status: completed, tag: Let's Encrypt/ACME, tag: PKI

#2130 [dhparam] Use `dhparam__openssl_options` in the host script as well
  ansible/roles/dhparam/templates/usr/local/lib/dhparam-generate-params.j2
Labels: bug, priority: high, status: completed, tag: security

#2152 [dhparam] Use custom openssl options in installed script
  ansible/roles/dhparam/templates/usr/local/lib/dhparam-generate-params.j2
Labels: bug, priority: medium, status: completed, tag: security

#2127 [cron] Fix some issues with cron job parameters
  ansible/roles/cron/tasks/main.yml
  ansible/roles/cron/templates/lookup/cron__combined_jobs.j2
  docs/ansible/roles/cron/defaults-detailed.rst
Labels: bug, priority: medium, status: completed

#2126 Move debops-contrib dropbear to debops
  CHANGELOG.rst
  ansible/debops-contrib-playbooks/README.rst
  ansible/playbooks/service/dropbear_initramfs.yml
  ansible/playbooks/sys/all.yml
  ansible/playbooks/sys/dropbear_initramfs.yml
  ansible/roles/dropbear_initramfs/defaults/main.yml
  ansible/roles/dropbear_initramfs/docs/changelog.rst
  ansible/roles/dropbear_initramfs/docs/copyright.rst
  ansible/roles/dropbear_initramfs/docs/includes/all.rst
  ansible/roles/dropbear_initramfs/docs/includes/role.rst
  ansible/roles/dropbear_initramfs/docs/index.rst
  ansible/roles/dropbear_initramfs/docs/introduction.rst
  ansible/roles/dropbear_initramfs/docs/playbooks/dropbear_initramfs.yml
  ansible/roles/dropbear_initramfs/docs/upgrade.rst
  ansible/roles/dropbear_initramfs/tasks/main.yml
  docs/ansible/role-index.rst
  docs/ansible/roles/dropbear_initramfs/defaults-detailed.rst
  docs/ansible/roles/dropbear_initramfs/design.rst
  docs/ansible/roles/dropbear_initramfs/examples/dropbear_initramfs__authorized_keys.yml
  docs/ansible/roles/dropbear_initramfs/examples/dropbear_initramfs__group_authorized_keys.yml
  docs/ansible/roles/dropbear_initramfs/examples/dropbear_initramfs__interfaces.yml
  docs/ansible/roles/dropbear_initramfs/getting-started.rst
  docs/ansible/roles/dropbear_initramfs/index.rst
  docs/ansible/roles/dropbear_initramfs/man_description.rst
  docs/ansible/roles/dropbear_initramfs/man_index.rst
  docs/ansible/roles/dropbear_initramfs/man_synopsis.rst
  docs/ansible/roles/dropbear_initramfs/related-projects.rst
  docs/ansible/roles/dropbear_initramfs/scripts/migrate-from-systemli.rootcrypto-to-debops.dropbear_initramfs
  docs/ansible/roles/dropbear_initramfs/upgrade.rst
  docs/includes/global.rst
  docs/news/upgrades.rst
Labels: change, priority: high, status: completed, tag: SSH

#2156 [gitlab] Redesign the role to use GitLab Omnibus
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/service/gitlab.yml
  ansible/roles/gitlab/COPYRIGHT
  ansible/roles/gitlab/defaults/main.yml
  ansible/roles/gitlab/files/script/gitlab-version2
  ansible/roles/gitlab/files/script/gitlab-version3
  ansible/roles/gitlab/handlers/main.yml
  ansible/roles/gitlab/meta/main.yml
  ansible/roles/gitlab/meta/watch-gitlab
  ansible/roles/gitlab/tasks/configure_gitaly.yml
  ansible/roles/gitlab/tasks/configure_gitlab-pages.yml
  ansible/roles/gitlab/tasks/configure_gitlab-shell.yml
  ansible/roles/gitlab/tasks/configure_gitlab-workhorse.yml
  ansible/roles/gitlab/tasks/configure_gitlab_ce.yml
  ansible/roles/gitlab/tasks/download_gitlab_ce.yml
  ansible/roles/gitlab/tasks/gitlab_ce_pre_upgrade.yml
  ansible/roles/gitlab/tasks/main.yml
  ansible/roles/gitlab/tasks/main_env.yml
  ansible/roles/gitlab/tasks/start_gitlab_ce.yml
  ansible/roles/gitlab/templates/etc/ansible/facts.d/gitlab.fact.j2
  ansible/roles/gitlab/templates/etc/cron.d/backup-gitlab-omnibus.j2
  ansible/roles/gitlab/templates/etc/default/gitlab-pages.j2
  ansible/roles/gitlab/templates/etc/default/gitlab.j2
  ansible/roles/gitlab/templates/etc/gitlab/gitlab.rb.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-gitaly.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-mailroom.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-pages.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-sidekiq.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-unicorn.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab-workhorse.service.j2
  ansible/roles/gitlab/templates/etc/systemd/system/gitlab.slice.j2
  ansible/roles/gitlab/templates/var/local/git/gitaly/config.toml.j2
  ansible/roles/gitlab/templates/var/local/git/gitconfig.j2
  ansible/roles/gitlab/templates/var/local/git/gitlab-shell/config.yml.j2
  ansible/roles/gitlab/templates/var/local/git/gitlab/config/database.postgresql.yml.j2
  ansible/roles/gitlab/templates/var/local/git/gitlab/config/gitlab.yml.j2
  ansible/roles/gitlab/templates/var/local/git/gitlab/config/initializers/rack_attack.rb.j2
  ansible/roles/gitlab/templates/var/local/git/gitlab/config/unicorn.rb.j2
  ansible/roles/global_handlers/handlers/gitlab.yml
  ansible/roles/global_handlers/handlers/main.yml
  docs/ansible/roles/gitlab/defaults-detailed.rst
  docs/ansible/roles/gitlab/getting-started.rst
  docs/ansible/roles/gitlab/index.rst
  docs/ansible/roles/gitlab/man_description.rst
  docs/ansible/roles/gitlab/man_index.rst
  docs/ansible/roles/gitlab/man_synopsis.rst
  docs/ansible/roles/gitlab/remote_db.rst
Labels: change, priority: medium, status: completed, tag: GitLab

#2157 Update Debian Bullseye release, ignore GitLab secrets
  CHANGELOG.rst
  ansible/roles/etckeeper/defaults/main.yml
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/ipxe/meta/watch-firmware-bullseye
  ansible/roles/ipxe/meta/watch-netboot-bullseye
Labels: change, priority: medium, status: completed, tag: version upgrade

#2155 [opensearch] Update OpenSearch to 2.1.0
  ansible/roles/opensearch/defaults/main.yml
  ansible/roles/opensearch/meta/watch-opensearch
Labels: priority: medium, tag: database, tag: version upgrade

#2154 Allow 3 tier apt packages installation for postfix
  ansible/roles/postfix/defaults/main.yml
  ansible/roles/postfix/tasks/main.yml
Labels: change, priority: medium, status: completed, tag: mail services

#2153 [roundcube] Update Roundcube to 1.5.3
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
  ansible/roles/roundcube/meta/watch-roundcubemail
Labels: priority: medium, tag: mail services, tag: version upgrade

#2125 [fhs] Add support for the *all/group/host* pattern to `fhs__*_directories`
  ansible/roles/fhs/defaults/main.yml
Labels: change, priority: medium, status: completed

#2124 [netbase] Use `==` for string comparisons in fact script
  ansible/roles/netbase/templates/etc/ansible/facts.d/netbase.fact.j2
Labels: bug, priority: high, status: completed, tag: DNS

#2123 [python] Decode subprocess output in fact script
  ansible/roles/python/templates/etc/ansible/facts.d/python.fact.j2
Labels: bug, priority: high, status: completed, tag: Ansible facts

#2120 [apt] Fix collection of `original_mirrors_deb_src` fact
  ansible/roles/apt/templates/etc/ansible/facts.d/apt.fact.j2
Labels: bug, priority: high, status: completed, tag: Ansible facts, tag: APT packages

#2119 Add note on ansible-console to delete realm files
  docs/ansible/roles/pki/getting-started.rst
Labels: documentation, priority: medium, status: completed, tag: PKI

#2116 [dokuwiki] User shell as a variable
  ansible/roles/dokuwiki/defaults/main.yml
  ansible/roles/dokuwiki/tasks/main.yml
Labels: new feature, priority: medium, status: completed

#2093 [pdns] No longer set UID/GID on pdns >= 4.3.0
  ansible/roles/pdns/defaults/main.yml
Labels: change, priority: low, status: completed, tag: DNS, tag: upkeep

#2088 [libvirt] No longer install virtual qemu-kvm pkg
  ansible/roles/libvirtd/defaults/main.yml
  ansible/roles/libvirtd_qemu/defaults/main.yml
Labels: change, priority: medium, status: completed, tag: upkeep, tag: virtualization

#2079 Update faq.rst with information about ssh
  docs/introduction/faq.rst
Labels: documentation, priority: medium, status: completed, tag: SSH

#2072 [docs] Fix typos in Prosody docs
  ansible/roles/prosody/defaults/main.yml
Labels: documentation, priority: medium, status: completed

#2070 [ferm] Expose all options from /etc/default/ferm
  ansible/roles/ferm/defaults/main.yml
  ansible/roles/ferm/templates/etc/default/ferm.j2
Labels: change, priority: medium, status: completed, tag: firewall

#2122 [environment] Fix fact handling
  ansible/roles/environment/defaults/main.yml
  ansible/roles/environment/tasks/main.yml
  ansible/roles/environment/templates/etc/ansible/facts.d/environment.fact.j2
  ansible/roles/environment/templates/lookup/environment__variables.j2
Labels: bug, status: completed

#2121 [core] Allow to remove/reset fact `ansible_controllers`
  ansible/roles/core/templates/etc/ansible/facts.d/core.fact.j2
Labels: bug, priority: medium, status: completed, tag: Ansible facts

#2115 Loop appends to a wrong variable
  ansible/roles/radvd/templates/etc/radvd.conf.j2
Labels: bug, priority: high, status: completed

#2068 fix #2067 by dropping the superfluous ipaddr call
  ansible/roles/ldap/templates/lookup/ldap__device_ip_addresses.j2
Labels: bug, priority: high, status: completed, tag: LDAP, tag: networking

#2064 Issue 2046 fixes
  CHANGELOG.rst
  ansible/roles/apt/defaults/main.yml
  ansible/roles/core/defaults/main.yml
Labels: bug, priority: high, tag: APT packages

#2062 [nginx] improve documentation nginx_ocsp_resolvers
  ansible/roles/nginx/defaults/main.yml
  docs/ansible/roles/nginx/defaults-detailed.rst
Labels: documentation, priority: medium, status: completed, tag: nginx

#2061 [owncloud] - nextcloud 23 compatibility
  ansible/roles/owncloud/tasks/setup_owncloud.yml
Labels: change, priority: medium, status: completed, tag: Nextcloud

#2060 Doc small fix
  docs/developer-guide/testing.rst
  src/debops/_data/templates/projectdir/legacy/debops.cfg.j2
Labels: documentation, priority: medium, status: completed

#2058 [postconf] Disable EHLO IP address check
  CHANGELOG.rst
  ansible/roles/postconf/defaults/main.yml
  docs/ansible/roles/postconf/getting-started.rst
Labels: bug, priority: high, status: completed, tag: mail services

#2033 [docs] Introduce top-level DNS documentation
  docs/ansible/roles/avahi/defaults-detailed.rst
  docs/ansible/roles/dnsmasq/defaults-detailed.rst
  docs/ansible/roles/icinga/deployment.rst
  docs/ansible/roles/imapproxy/getting-started.rst
  docs/ansible/roles/nullmailer/getting-started.rst
  docs/ansible/roles/roundcube/getting-started.rst
  docs/ansible/roles/rsyslog/getting-started.rst
  docs/ansible/roles/slapd/guide-multi-master-replication.rst
  docs/index.rst
  docs/user-guide/dns-configuration.rst
Labels: documentation, priority: high, status: completed, tag: DNS

#2075 Introducing Miniflux service to DebOps
  .gitlab-ci.yml
  ansible/playbooks/app/all.yml
  ansible/playbooks/app/miniflux.yml
  ansible/playbooks/service/miniflux.yml
  ansible/roles/miniflux/COPYRIGHT
  ansible/roles/miniflux/defaults/main.yml
  ansible/roles/miniflux/meta/main.yml
  ansible/roles/miniflux/meta/watch-miniflux
  ansible/roles/miniflux/tasks/main.yml
  ansible/roles/miniflux/templates/etc/miniflux.conf.j2
  ansible/roles/miniflux/templates/etc/systemd/system/miniflux.service.j2
Labels: new feature, priority: medium, tag: application

#2158 Add 'debops.miniflux' Ansible role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/app/all.yml
  ansible/playbooks/app/miniflux.yml
  ansible/playbooks/service/miniflux.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/global_handlers/handlers/miniflux.yml
  ansible/roles/miniflux/COPYRIGHT
  ansible/roles/miniflux/defaults/main.yml
  ansible/roles/miniflux/meta/main.yml
  ansible/roles/miniflux/meta/watch-miniflux
  ansible/roles/miniflux/tasks/main.yml
  ansible/roles/miniflux/templates/etc/ansible/facts.d/miniflux.fact.j2
  ansible/roles/miniflux/templates/etc/miniflux.conf.j2
  ansible/roles/miniflux/templates/etc/systemd/system/miniflux.service.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/miniflux/defaults-detailed.rst
  docs/ansible/roles/miniflux/getting-started.rst
  docs/ansible/roles/miniflux/index.rst
  docs/ansible/roles/miniflux/man_description.rst
  docs/ansible/roles/miniflux/man_index.rst
  docs/ansible/roles/miniflux/man_synopsis.rst
  docs/user-guide/dns-configuration.rst
Labels: new feature, priority: medium, status: completed, tag: application

#1891 roundcube: Lock contextmenu-plugin version for roundcube 1.4.x
  CHANGELOG.rst
  ansible/roles/roundcube/defaults/main.yml
Labels: bug, status: completed, tag: mail services

#1997 [icinga] Improve initial host registration
  ansible/roles/icinga/defaults/main.yml
  ansible/roles/icinga/tasks/main.yml
  docs/ansible/roles/icinga/deployment.rst
Labels: new feature, priority: high, tag: monitoring

#2164 Improvements to Icinga service deployment
  CHANGELOG.rst
  ansible/roles/icinga/defaults/main.yml
  ansible/roles/icinga/tasks/main.yml
  ansible/roles/icinga_web/defaults/main.yml
  ansible/roles/icinga_web/tasks/main.yml
  docs/ansible/roles/icinga/deployment.rst
  docs/ansible/roles/icinga_web/defaults-detailed.rst
Labels: change, priority: high, status: completed, tag: monitoring

#2159 [nginx] Document further advantages with waiting for network
  ansible/roles/nginx/templates/etc/systemd/system/nginx.service.d/wait-for-network.conf.j2
Labels: documentation, priority: medium, status: completed, tag: nginx

#2163 [dovecot] Fix backslashes in regex_replace
  ansible/roles/dovecot/defaults/main.yml
Labels: bug, priority: high, status: completed, tag: mail services
