Repository debops/debops, pull requests merged in 2023-02, with the labels that each got.

#2279 Refresh SSH service configuration, improve support for socket activation
  CHANGELOG.rst
  ansible/roles/global_handlers/handlers/sshd.yml
  ansible/roles/sshd/defaults/main.yml
  ansible/roles/sshd/tasks/main.yml
  ansible/roles/sshd/templates/etc/ansible/facts.d/sshd.fact.j2
  ansible/roles/sshd/templates/etc/ssh/sshd_config.j2
  ansible/roles/sshd/templates/etc/systemd/system/ssh.socket.d/listen.conf.j2
  docs/ansible/roles/sshd/defaults-detailed.rst
  docs/ansible/roles/sshd/getting-started.rst
  docs/ansible/roles/sshd/index.rst
  docs/ansible/roles/sshd/man_index.rst
  docs/news/upgrades.rst
Labels: change, priority: medium, status: completed, tag: SSH

#2280 Fix some of the issues detected by newest ansible-lint
  .ansible-lint
  ansible/collections/ansible_collections/debops/debops/CHANGELOG.rst
  ansible/collections/ansible_collections/debops/debops/galaxy.yml
  ansible/playbooks/layer/common.yml
  ansible/playbooks/ldap/get-uuid.yml
  ansible/roles/apparmor/tests/test.yml
  ansible/roles/rails_deploy/tasks/main.yml
  docs/ansible/roles/apt_cacher_ng/examples/apt_cacher_ng-apparmor.yml
Labels: bug, priority: high, status: completed, tag: Continuous Integration

#2281 fix(sshd): use "init" for parameter to uncomment when set
  ansible/roles/apparmor/tests/inventory
  ansible/roles/apparmor/tests/test.yml
  ansible/roles/sshd/defaults/main.yml
  ansible/roles/system_groups/defaults/main.yml
Labels: change

#2282 More fixes to linting issues found by 'ansible-lint'
  ansible/debops-contrib-playbooks/service/dnsmasq.yml
  ansible/debops-contrib-playbooks/service/volkszaehler-apache.yml
  ansible/debops-contrib-playbooks/service/volkszaehler-nginx.yml
  ansible/playbooks/ldap/get-uuid.yml
  ansible/playbooks/ldap/init-directory.yml
  ansible/playbooks/ldap/save-credential.yml
  ansible/playbooks/tools/6to4.yml
  ansible/playbooks/tools/debug.yml
  ansible/playbooks/tools/dist-upgrade.yml
  ansible/roles/apt/tasks/main.yml
  ansible/roles/elasticsearch/tasks/authentication.yml
  ansible/roles/environment/tasks/main.yml
  ansible/roles/keyring/tasks/main.yml
  ansible/roles/rabbitmq_server/tasks/main.yml
  ansible/roles/rails_deploy/tasks/deploy_keys.yml
  ansible/roles/sshd/defaults/main.yml
  docs/ansible/roles/dnsmasq/examples/dnsmasq-apparmor.yml
  docs/ansible/roles/docker_server/examples/docker-redis.yml
Labels: change, priority: medium, status: completed, tag: Continuous Integration
