Repository debops/debops, pull requests merged in 2023-06, with the labels that each got.

#2363 RFC: Switch all Debian releases : bookworm is now stable
  ansible/playbooks/tools/dist-upgrade.yml
  ansible/roles/apt/defaults/main.yml
  ansible/roles/apt_preferences/defaults/main.yml
  ansible/roles/preseed/defaults/main.yml
  ansible/roles/reprepro/defaults/main.yml
Labels: change, priority: medium, status: completed, tag: upkeep

#2368 Improvements in Debian Bookworm support
  CHANGELOG.rst
  ansible/roles/auth/defaults/main.yml
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/ipxe/meta/watch-firmware-bookworm
  ansible/roles/ipxe/meta/watch-netboot-bookworm
  ansible/roles/resolved/defaults/main.yml
  ansible/roles/resolved/tasks/main.yml
  ansible/roles/resolved/templates/etc/systemd/resolved.conf.d/fallback-dns.conf.j2
  docs/ansible/roles/resolved/getting-started.rst
Labels: change, priority: high, status: completed, tag: DNS, tag: upkeep

#2374 [ifupdown]: order iface@ service after apparmor
  ansible/roles/ifupdown/templates/etc/systemd/system/iface@.service.j2
Labels: change, priority: medium, status: completed, tag: networking

#2373 [ifupdown]: escape and unescape interface names in systemd unit name
  ansible/roles/ifupdown/files/script/ifupdown-reconfigure-interfaces
  ansible/roles/ifupdown/templates/etc/systemd/system/iface@.service.j2
  ansible/roles/ifupdown/templates/etc/systemd/system/ifup-allow-boot.service.j2
Labels: change, priority: high, status: completed, tag: networking

#2369 [sshd] set ChallengeResponseAuthentication to False by default
  ansible/roles/sshd/defaults/main.yml
Labels: bug, priority: high, status: completed, tag: security, tag: SSH

#2376 New sysctl filename - 99-protect-links.conf
  ansible/roles/sysctl/defaults/main.yml
Labels: change, priority: high, tag: upkeep, tag: kernel

#2375 [sshd] set ChallengeResponseAuthentication fo False by default
  ansible/roles/sshd/defaults/main.yml
Labels: change, priority: high, status: completed, tag: SSH
