Repository debops/debops, pull requests merged in 2023-05, with the labels that each got.

#2343 [system_users] Add support for NSS-based lookups to getent_passwd.py3
  ansible/roles/system_users/files/script/getent_passwd.py3
Labels: change, priority: medium, status: completed

#2346 [ci] Fix issues found by ansible-lint v6.16.0
  ansible/roles/etckeeper/tasks/main.yml
  ansible/roles/postgresql_server/tasks/manage_clusters.yml
Labels: change, priority: medium, status: completed, tag: Continuous Integration

#2351 Add 'apt_mirror' Ansible role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/layer/srv.yml
  ansible/playbooks/service/apt_mirror.yml
  ansible/roles/apt_mirror/COPYRIGHT
  ansible/roles/apt_mirror/defaults/main.yml
  ansible/roles/apt_mirror/meta/main.yml
  ansible/roles/apt_mirror/tasks/main.yml
  ansible/roles/apt_mirror/templates/etc/ansible/facts.d/apt_mirror.fact.j2
  ansible/roles/apt_mirror/templates/etc/apt/mirror.list.j2
  ansible/roles/apt_mirror/templates/etc/cron.d/apt-mirror.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/apt_mirror/defaults-detailed.rst
  docs/ansible/roles/apt_mirror/getting-started.rst
  docs/ansible/roles/apt_mirror/index.rst
  docs/ansible/roles/apt_mirror/man_description.rst
  docs/ansible/roles/apt_mirror/man_index.rst
  docs/ansible/roles/apt_mirror/man_synopsis.rst
Labels: new feature, priority: medium, status: completed, tag: APT packages

#2352 Fix warnings found by latest ansible-lint release
  ansible/debops-contrib-playbooks/service/all.yml
  ansible/debops-contrib-playbooks/service/foodsoft.yml
  ansible/debops-contrib-playbooks/service/homeassistant.yml
  ansible/debops-contrib-playbooks/service/volkszaehler.yml
  ansible/roles/apparmor/tasks/handle_locals.yml
  ansible/roles/apparmor/tasks/handle_tunables.yml
  ansible/roles/apparmor/templates/etc/apparmor.d/snippet.j2
  ansible/roles/core/tasks/main.yml
  ansible/roles/freeradius/tasks/main.yml
  ansible/roles/keyring/tasks/main.yml
  ansible/roles/lxc/tasks/main.yml
  ansible/roles/machine/tasks/main.yml
  ansible/roles/pam_access/tasks/main.yml
  ansible/roles/rails_deploy/tasks/deploy.yml
  ansible/roles/rails_deploy/tasks/deploy_keys.yml
Labels: change, priority: medium, status: completed, tag: Continuous Integration

#2350 Fix libvirtd kvm packages
  ansible/roles/libvirtd/defaults/main.yml
Labels: change, priority: high, tag: virtualization

#2355 Fixes ansible shell with pipefail
  ansible/roles/controller/handlers/main.yml
  ansible/roles/owncloud/tasks/tarball.yml
  ansible/roles/postwhite/handlers/main.yml
Labels: change, priority: medium, status: completed

#2358 Add new script to make stable releases easier
  bin/new-stable-release
Labels: internal, priority: medium, status: completed
