Repository debops/debops, pull requests merged in 2024-09, with the labels that each got.

#2506 fix typo in icinga handler
  ansible/roles/icinga/handlers/main.yml
Labels: bug, priority: high, status: completed

#2519 Implement various upgrades and fixes in multiple roles
  CHANGELOG.rst
  ansible/roles/apt_install/tasks/main.yml
  ansible/roles/debconf/defaults/main.yml
  ansible/roles/debconf/tasks/main.yml
  ansible/roles/dpkg_cleanup/templates/usr/local/lib/dpkg-cleanup/package.j2
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/networkd/defaults/main.yml
  ansible/roles/networkd/handlers/main.yml
  ansible/roles/networkd/tasks/main.yml
  ansible/roles/pki/files/secret/pki/lib/pki-authority
  ansible/roles/pki/files/usr/local/lib/pki/pki-realm
  ansible/roles/pki/tasks/main.yml
  ansible/roles/pki/templates/etc/pki/realms/realm/config/environment.j2
  ansible/roles/postgresql_server/defaults/main.yml
  ansible/roles/postgresql_server/templates/etc/default/autopostgresqlbackup.j2
  ansible/roles/postgresql_server/templates/usr/sbin/autopostgresqlbackup.j2
  ansible/roles/rabbitmq_server/tasks/main.yml
  ansible/roles/rails_deploy/templates/etc/init.d/service.j2
  ansible/roles/rsyslog/defaults/main.yml
  ansible/roles/zabbix_agent/templates/etc/ansible/facts.d/zabbix_agent.fact.j2
  docs/ansible/roles/networkd/getting-started.rst
  docs/ansible/roles/pki/defaults-detailed.rst
  docs/ansible/roles/pki/pki-realms.rst
Labels: change, priority: medium, status: completed, tag: logging, tag: PostgreSQL, tag: networking, tag: PKI

#2518 Add separate option enabling to set basedir variable
  ansible/roles/reprepro/templates/home/reprepro/repositories/instance/conf/options.j2
Labels: change, priority: medium, status: completed

#2517 Update installation documentation with pipx instead of pip
  INSTALL.rst
  README.md
  setup.py
Labels: documentation, priority: high, status: completed

#2505 Update make-collection
  lib/ansible-galaxy/make-collection
Labels: bug, priority: high, status: completed

#2387 no boot interface at boot - [ifupdown] Fix breakage introduced by hyphen support fixup.
  ansible/roles/ifupdown/templates/etc/systemd/system/ifup-allow-boot.service.j2
Labels: bug, priority: high, status: completed, tag: networking

#2520 Unbound: change ipsubnet to ansible.utils.ipsubnet
  ansible/roles/unbound/templates/etc/unbound/unbound.conf.d/zone.conf.j2
Labels: change, priority: medium, status: completed

#2500 [ntp] Fix ntp__daemon_enabled ansible system capabilities check
  ansible/roles/ntp/defaults/main.yml
Labels: bug, priority: high, status: completed

#2521 [ipxe] Update Debian Bullseye/Bookworm versions
  CHANGELOG.rst
  ansible/roles/ipxe/defaults/main.yml
  ansible/roles/ipxe/meta/watch-firmware-bookworm
  ansible/roles/ipxe/meta/watch-firmware-bullseye
  ansible/roles/ipxe/meta/watch-netboot-bookworm
  ansible/roles/ipxe/meta/watch-netboot-bullseye
Labels: change, priority: high, status: completed, tag: upkeep

#2499 [pam_access] fix issue with unknown variable
  ansible/roles/pam_access/tasks/main.yml
Labels: bug, priority: high, status: completed

#2522 Add support for read-only Fridays in DebOps script
  CHANGELOG.rst
  src/debops/_data/templates/projectdir/modern/project.yml.j2
  src/debops/ansibleplaybookrunner.py
Labels: new feature, priority: medium, status: completed, tag: DebOps script

#2482 [grub] setting grub user is broken
  ansible/roles/grub/templates/etc/grub.d/01_users.j2
Labels: bug, priority: high, status: completed, tag: security, tag: provisioning

#2523 Update Copyright dates and release schedule of DebOps
  CHANGELOG.rst
  docs/conf.py
  docs/news/releases.rst
Labels: documentation, priority: medium, status: completed

#2389 Fix disable apache vhost if enabled is not set
  ansible/roles/apache/tasks/main.yml
Labels: bug, priority: medium, status: completed, tag: webserver

#2525 chore(volkszaehler): remove role, switch to Grafana and InfluxDB
  CHANGELOG.rst
  CODEOWNERS
  ansible/debops-contrib-playbooks/README.rst
  ansible/debops-contrib-playbooks/service/all.yml
  ansible/debops-contrib-playbooks/service/volkszaehler-apache.yml
  ansible/debops-contrib-playbooks/service/volkszaehler-nginx.yml
  ansible/debops-contrib-playbooks/service/volkszaehler.yml
  ansible/roles/volkszaehler/COPYRIGHT
  ansible/roles/volkszaehler/defaults/main.yml
  ansible/roles/volkszaehler/docs/changelog.rst
  ansible/roles/volkszaehler/docs/copyright.rst
  ansible/roles/volkszaehler/docs/getting-started.rst
  ansible/roles/volkszaehler/docs/includes/all.rst
  ansible/roles/volkszaehler/docs/includes/role.rst
  ansible/roles/volkszaehler/docs/index.rst
  ansible/roles/volkszaehler/docs/introduction.rst
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler-apache.yml
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler-nginx.yml
  ansible/roles/volkszaehler/docs/playbooks/volkszaehler.yml
  ansible/roles/volkszaehler/meta/main.yml
  ansible/roles/volkszaehler/tasks/main.yml
  ansible/roles/volkszaehler/tasks/main_env.yml
  ansible/roles/volkszaehler/templates/etc/ansible/facts.d/volkszaehler.fact.j2
  ansible/roles/volkszaehler/templates/etc/volkszaehler.conf.php.j2
  docs/ansible/role-index.rst
  docs/includes/global.rst
  docs/user-guide/dns-configuration.rst
  lib/ansible-galaxy/make-collection
Labels: change, priority: medium, status: completed

#2524 chore(bitcoind): remove role because it is unmaintained
  CHANGELOG.rst
  CODEOWNERS
  ansible/debops-contrib-playbooks/README.rst
  ansible/debops-contrib-playbooks/service/all.yml
  ansible/debops-contrib-playbooks/service/bitcoind.yml
  ansible/roles/bitcoind/COPYRIGHT
  ansible/roles/bitcoind/defaults/main.yml
  ansible/roles/bitcoind/docs/changelog.rst
  ansible/roles/bitcoind/docs/copyright.rst
  ansible/roles/bitcoind/docs/getting-started.rst
  ansible/roles/bitcoind/docs/includes/all.rst
  ansible/roles/bitcoind/docs/includes/role.rst
  ansible/roles/bitcoind/docs/index.rst
  ansible/roles/bitcoind/docs/introduction.rst
  ansible/roles/bitcoind/docs/playbooks/bitcoind.yml
  ansible/roles/bitcoind/handlers/main.yml
  ansible/roles/bitcoind/meta/main.yml
  ansible/roles/bitcoind/tasks/main.yml
  ansible/roles/bitcoind/templates/etc/bitcoin/bitcoin.conf.j2
  ansible/roles/bitcoind/templates/etc/systemd/system/bitcoind.service.j2
  docs/ansible/role-index.rst
  docs/includes/global.rst
  lib/ansible-galaxy/make-collection
Labels: change, priority: medium, status: completed

#2526 Enabling build of dropbear_initramfs role
  lib/ansible-galaxy/make-collection
Labels: change, priority: high, status: completed, tag: Ansible Collection

#2485 Support follow parameter for authorized_keys
  ansible/roles/authorized_keys/tasks/main.yml
  ansible/roles/root_account/defaults/main.yml
  ansible/roles/root_account/tasks/main.yml
  ansible/roles/system_users/tasks/main.yml
  ansible/roles/users/tasks/main.yml
  docs/ansible/roles/authorized_keys/defaults-detailed.rst
  docs/ansible/roles/system_users/defaults-detailed.rst
  docs/ansible/roles/users/defaults-detailed.rst
Labels: change, priority: medium, status: completed

#2479 Fix #2478 - Dropbear initramfs: Renamed config path
  ansible/roles/dropbear_initramfs/defaults/main.yml
  ansible/roles/dropbear_initramfs/tasks/main.yml
  ansible/roles/dropbear_initramfs/templates/etc/dropbear-initramfs/config.j2
  ansible/roles/dropbear_initramfs/templates/etc/dropbear/initramfs/dropbear.conf.j2
Labels: change, priority: high, status: completed, tag: provisioning

#2480 [onwcloud] Add missing password for postgresql
  ansible/roles/owncloud/defaults/main.yml
Labels: bug, priority: high, status: completed, tag: PostgreSQL, tag: Nextcloud

#2481 [dovecot] Add ability to list users using doveadm
  CHANGELOG.rst
  ansible/roles/dovecot/defaults/main.yml
  ansible/roles/dovecot/templates/etc/dovecot/dovecot-ldap-userdb.conf.j2
Labels: new feature, priority: medium, status: completed, tag: mail services

#2529 Add new role, 'debops.nixos'
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/nixos.yml
  ansible/roles/nixos/COPYRIGHT
  ansible/roles/nixos/defaults/main.yml
  ansible/roles/nixos/handlers/main.yml
  ansible/roles/nixos/meta/main.yml
  ansible/roles/nixos/tasks/main.yml
  ansible/roles/nixos/tasks/nixos/post_main.yml
  ansible/roles/nixos/tasks/nixos/pre_main.yml
  ansible/roles/nixos/templates/etc/nixos/template.nix.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/nixos/defaults-detailed.rst
  docs/ansible/roles/nixos/getting-started.rst
  docs/ansible/roles/nixos/index.rst
  docs/ansible/roles/nixos/man_description.rst
  docs/ansible/roles/nixos/man_index.rst
  docs/ansible/roles/nixos/man_synopsis.rst
Labels: new feature, priority: medium, status: completed
