Repository debops/debops, pull requests merged in 2024-08, with the labels that each got.

#2509 feat(proc_hidepid): ensure hidepid is disabled when libvirtd is used
  ansible/roles/proc_hidepid/defaults/main.yml
  docs/ansible/roles/proc_hidepid/getting-started.rst
Labels: change, priority: medium, status: completed, tag: security, tag: monitoring

#2515 enable override template in sshd role
  ansible/roles/sshd/tasks/main.yml
Labels: change, priority: medium, status: completed, tag: SSH

#2516 Fix issues in the 'debops.swapfile' role
  CHANGELOG.rst
  ansible/roles/swapfile/tasks/main.yml
Labels: bug, priority: high, status: completed
