Repository debops/debops, pull requests merged in 2024-10, with the labels that each got.

#2530 Add 'debops.influxdb2' role
  .gitlab-ci.yml
  CHANGELOG.rst
  ansible/playbooks/layer/srv.yml
  ansible/playbooks/service/influxdb2.yml
  ansible/roles/global_handlers/handlers/influxdb2.yml
  ansible/roles/global_handlers/handlers/main.yml
  ansible/roles/influxdb2/COPYRIGHT
  ansible/roles/influxdb2/defaults/main.yml
  ansible/roles/influxdb2/meta/main.yml
  ansible/roles/influxdb2/tasks/main.yml
  ansible/roles/influxdb2/templates/etc/ansible/facts.d/influxdb2.fact.j2
  ansible/roles/influxdb2/templates/etc/influxdb/config.toml.j2
  docs/ansible/role-index.rst
  docs/ansible/roles/influxdb2/defaults-detailed.rst
  docs/ansible/roles/influxdb2/getting-started.rst
  docs/ansible/roles/influxdb2/index.rst
  docs/ansible/roles/influxdb2/man_description.rst
  docs/ansible/roles/influxdb2/man_index.rst
  docs/ansible/roles/influxdb2/man_synopsis.rst
Labels: new feature, priority: medium, status: completed, tag: database, tag: monitoring, tag: InfluxData

#2531 Small fixes in multple roles
  .yamllint
  CHANGELOG.rst
  INSTALL.rst
  ansible/playbooks/layer/common.yml
  ansible/playbooks/service/resolved.yml
  ansible/roles/debconf/meta/main.yml
  ansible/roles/lvm/vars/lvm_config_2.02.168.yml
  ansible/roles/lvm/vars/lvm_config_2.03.02.yml
  ansible/roles/resolved/defaults/main.yml
  ansible/roles/root_account/tasks/main.yml
  ansible/roles/system_users/tasks/main.yml
  ansible/roles/users/tasks/main.yml
  docs/ansible/roles/yadm/getting-started.rst
  src/debops/projectdir.py
Labels: change, priority: high, status: completed, tag: Continuous Integration, tag: DebOps script

#2323 [bind] Minor fixes
  ansible/roles/bind/defaults/main.yml
  ansible/roles/bind/files/usr/local/sbin/debops-bind-snapshot
  docs/user-guide/dns-configuration.rst
Labels: change, priority: medium, status: completed, tag: DNS

#2497 [gitlab_runner] Fix compatible with GitLab 17.0 or higher
  ansible/roles/gitlab_runner/defaults/main.yml
  ansible/roles/gitlab_runner/tasks/main.yml
Labels: change, priority: medium, tag: GitLab

#2447 Implement CI pipeline for roles and playbooks
  .github/workflows/debops-ci-pipeline.yml
  .github/workflows/prepare-ci-pipeline/action.yml
  requirements-integration.txt
Labels: change, priority: high, status: completed, tag: Continuous Integration

#2539 [ci] Don't pin versions of specific packages in CI
  .github/workflows/continuous-integration.yml
  .github/workflows/prepare-ci-pipeline/action.yml
  docs/conf.py
  requirements-integration.txt
  src/debops/cli.py
Labels: change, priority: high, status: completed, tag: Continuous Integration

#2446 Flatten directory paths for docker-gen role
  ansible/roles/docker_gen/tasks/main.yml
Labels: bug, priority: high, status: completed

#2541 [docs] Improve 'nixos' role documentation
  docs/ansible/roles/nixos/defaults-detailed.rst
  docs/ansible/roles/nixos/examples/flake-configuration.yml
  docs/ansible/roles/nixos/getting-started.rst
Labels: documentation, priority: medium, status: completed

#2534 Fixed bug in dist-upgrade.yml
  ansible/playbooks/tools/dist-upgrade.yml
Labels: bug, priority: medium, status: completed, tag: version upgrade

#2476 Fix logic in `owncloud__do_autosetup`
  ansible/roles/owncloud/tasks/setup_owncloud.yml
Labels: bug, priority: high, status: completed, tag: Nextcloud

#2475 Use template_src to overrive of nginx templates
  ansible/roles/nginx/tasks/main.yml
  ansible/roles/nginx/tasks/nginx_configs.yml
  ansible/roles/nginx/tasks/nginx_servers.yml
Labels: change, priority: medium, status: completed, tag: nginx

#2465 Restart fail2ban after ferm restart
  ansible/roles/ferm/defaults/main.yml
Labels: bug, priority: high, status: completed, tag: firewall

#2460 Avoid an error if ferm rules are empty
  ansible/roles/ferm/tasks/main.yml
Labels: bug, priority: medium, status: completed, tag: firewall

#2544 [nginx] Fix syntax error
  ansible/roles/nginx/tasks/nginx_configs.yml
Labels: bug, priority: high, status: completed, tag: nginx

#2545 Small bugfixes
  CHANGELOG.rst
  Dockerfile
  ansible/roles/nginx/tasks/nginx_servers.yml
  docs/ansible/roles/python/getting-started.rst
Labels: change, priority: medium, status: completed

#2160 [rspamd] Fix PEP632 deprecation of distutils
  ansible/roles/rspamd/files/usr/local/sbin/rspamd-dkim-keygen
  ansible/roles/rspamd/files/usr/local/sbin/rspamd-dkim-update
Labels: change, priority: high, status: completed, tag: mail services

#2451 workaround bag due to docker/network issue - https://bugs.debian.org/…
  ansible/roles/snmpd/files/etc/systemd/system/snmpd.service
Labels: change, priority: medium, status: completed, tag: networking, tag: monitoring

#2450 [docs] Typo fix in dovecot getting started
  docs/ansible/roles/dovecot/getting-started.rst
Labels: documentation, priority: medium, status: completed

#2440 Fix pid max 32bits
  ansible/roles/core/templates/etc/ansible/facts.d/core.fact.j2
  ansible/roles/sysctl/defaults/main.yml
Labels: change, priority: high, status: completed

#2427 [nginx] Remove systemd override for nginx.service
  ansible/roles/nginx/tasks/main.yml
  ansible/roles/nginx/templates/etc/systemd/system/nginx.service.d/wait-for-network.conf.j2
Labels: change, priority: medium, status: completed, tag: nginx

#2441 RCF: [ifupdown] Fix bridges down at boot with Debian bookworm systemd
  ansible/roles/ifupdown/templates/etc/systemd/system/iface@.service.j2
Labels: change, priority: high, status: completed, tag: networking
